## **Yesterday, we learnt a little about the very useful library Pandas widely used for Data Analysis. It is time to put the many utilities of this library in front of our eyes. We will be performing following manipulations and exploration of our data:**

* ### Indexing and slicing operations
* ### Manipulating columns
* ### Exploring unique and missing values

In [1]:
# Import pandas package
import pandas as pd
import numpy as np

## Let us read our data first

### <u>Loading a CSV (Comma-Separated Values) file</u>

In [2]:
# loading csv File

df=pd.read_csv(r"C:\Users\LakshmanAIMLHYD\Desktop\AI&ML(7-8)\2.EDA\imdb_pandas_practice_dataset.csv")

df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,Hot Tub Time Machine 2,14000000,"[{""name"": ""Comedy""}]",NaN,tt2637294,en,Hot Tub Time Machine 2,Time travel comedy.,6.575393,...,2/20/15,93.0,"[{""name"": ""English""}]",Released,The Laws of Space and Time,Hot Tub Time Machine 2,time travel,"[{""name"": ""Rob Corddry""}]","[{""name"": ""Steve Pink"", ""job"": ""Director""}]",12314651
1,2,The Princess Diaries 2: Royal Engagement,40000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,A princess prepares for marriage.,8.248895,...,8/6/04,113.0,"[{""name"": ""English""}]",Released,It can take a lifetime to find true love.,The Princess Diaries 2: Royal Engagement,princess|royalty,"[{""name"": ""Anne Hathaway""}]","[{""name"": ""Garry Marshall"", ""job"": ""Director""}]",95149435
2,3,Whiplash,3300000,"[{""name"": ""Drama""}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,A young drummer faces a ruthless instructor.,64.299990,...,10/10/14,105.0,"[{""name"": ""English""}]",Released,The road to greatness can take you to the edge.,Whiplash,jazz|music,"[{""name"": ""Miles Teller""}]","[{""name"": ""Damien Chazelle"", ""job"": ""Director""}]",13092000
3,4,Kahaani,1200000,"[{""name"": ""Thriller""}, {""name"": ""Drama""}]",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,A woman searches for her missing husband in Ko...,3.174936,...,3/9/12,122.0,"[{""name"": ""English|Hindi""}]",Released,NaN,Kahaani,mystery|kolkata,"[{""name"": ""Vidya Balan""}]","[{""name"": ""Sujoy Ghosh"", ""job"": ""Director""}]",16000000
4,5,Marine Boy,0,"[{""name"": ""Action""}, {""name"": ""Thriller""}]",NaN,tt1380152,ko,Marine Boy,A former swimmer becomes involved in crime.,1.148070,...,2/5/09,118.0,"[{""name"": ""Korean""}]",Released,NaN,Marine Boy,NaN,"[{""name"": ""Kim Kang-woo""}]","[{""name"": ""Yoon Jong-chan"", ""job"": ""Director""}]",3923970

In [3]:
df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [4]:
df.shape

(30, 23)

In [5]:
df.tail()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
25,26,RRR,550000000,"[{""name"": ""Action""}, {""name"": ""Drama""}]",NaN,tt8178634,te,RRR,Two revolutionaries form an unlikely friendship.,60.3,...,3/25/22,187.0,"[{""name"": ""Telugu""}]",Released,Rise. Roar. Revolt.,RRR,friendship|revolution,"[{""name"": ""N. T. Rama Rao Jr.""}]","[{""name"": ""S. S. Rajamouli"", ""job"": ""Director""}]",1200000000
26,27,Bahubali 2: The Conclusion,250000000,"[{""name"": ""Action""}, {""name"": ""Drama""}]",NaN,tt4849438,te,Baahubali 2: The Conclusion,A kingdom seeks answers and revenge.,52.9,...,4/28/17,168.0,"[{""name"": ""Telugu""}]",Released,Why did Kattappa kill Baahubali?,Baahubali 2: The Conclusion,kingdom|war,"[{""name"": ""Prabhas""}]","[{""name"": ""S. S. Rajamouli"", ""job"": ""Director""}]",1810000000
27,28,Joker,55000000,"[{""name"": ""Crime""}, {""name"": ""Drama""}]",NaN,tt7286456,en,Joker,A failed comedian descends into chaos.,70.9,...,10/4/19,122.0,"[{""name"": ""English""}]",Released,Put on a happy face.,Joker,joker|crime,"[{""name"": ""Joaquin Phoenix""}]","[{""name"": ""Todd Phillips"", ""job"": ""Director""}]",1074251311
28,29,La La Land,30000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}, {""name...",NaN,tt3783958,en,La La Land,A musician and actress pursue dreams in Los An...,35.8,...,12/25/16,128.0,"[{""name"": ""English""}]",Released,Here's to the fools who dream.,La La Land,music|los angeles,"[{""name"": ""Ryan Gosling""}]","[{""name"": ""Damien Chazelle"", ""job"": ""Director""}]",472000000
29,30,Dilwale Dulhania Le Jayenge,40000000,"[{""name"": ""Drama""}, {""name"": ""Romance""}]",NaN,tt0112870,hi,Dilwale Dulhania Le Jayenge,A young couple challenges family expectations.,20.6,...,10/20/95,181.0,"[{""name"": ""Hindi""}]",Released,Come... Fall in love.,Dilwale Dulhania Le Jayenge,romance|family,"[{""name"": ""Shah Rukh Khan""}]","[{""name"": ""Aditya Chopra"", ""job"": ""Director""}]",120000000

In [6]:
df.production_countries.value_counts()

production_countries
[{"iso_3166_1": "US"}]    18
[{"iso_3166_1": "IN"}]     8
[{"iso_3166_1": "KR"}]     2
[{"iso_3166_1": "SE"}]     1
[{"iso_3166_1": "JP"}]     1
Name: count, dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     30 non-null     int64
 1   belongs_to_collection  30 non-null     object
 2   budget                 30 non-null     int64
 3   genres                 29 non-null     object
 4   homepage               9 non-null      object
 5   imdb_id                30 non-null     object
 6   original_language      30 non-null     object
 7   original_title         30 non-null     object
 8   overview               30 non-null     object
 9   popularity             30 non-null     float64
 10  poster_path            29 non-null     object
 11  production_companies   27 non-null     object
 12  production_countries   30 non-null     object
 13  release_date           30 non-null     object
 14  runtime                29 non-null     float64
 15  spoken_languages       30 non-null     object
 16  status                 30 non-null     object
 17  tagline                25 non-null     object
 18  title                  30 non-null     object
 19  Keywords               29 non-null     object
 20  cast                   30 non-null     object
 21  crew                   30 non-null     object
 22  revenue                30 non-null     int64
dtypes: float64(2), int64(3), object(18)
memory usage: 5.5+ KB

# **Data set info / data insights**

- genres    has 1 null value 

- homepage has 21 null values

- imdb_id  has datatype wrong 

- poster_path  has one missing value

- release_date has wrong type of data

- runtime  has one null value

- tagline has 5 null values

- Keywords has one null value

# <u>**<code>describe()</code>**</u>

## This method gives the overall descriptive summary of the dataframe. This works only for numerical columns

In [8]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
id,30.0,1.550000e+01,8.803408e+00,1.00000,8.250000e+00,1.550000e+01,2.275000e+01,3.000000e+01
budget,30.0,1.009633e+08,1.492895e+08,0.00000,1.205000e+07,4.000000e+07,1.400000e+08,5.500000e+08
popularity,30.0,3.904264e+01,3.146144e+01,1.14807,1.100908e+01,3.035000e+01,6.925000e+01,9.530000e+01
runtime,29.0,1.326207e+02,4.006371e+01,0.00000,1.060000e+02,1.280000e+02,1.680000e+02,1.940000e+02
revenue,30.0,5.554160e+08,7.579332e+08,0.00000,2.325000e+07,2.347086e+08,8.046823e+08,2.797501e+09

In [9]:
df.describe(include="object").T

,count,unique,top,freq
belongs_to_collection,30,30,Hot Tub Time Machine 2,1
genres,29,20,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",4
homepage,9,9,http://sonyclassics.com/whiplash/,1
imdb_id,30,30,tt2637294,1
original_language,30,7,en,18
original_title,30,30,Hot Tub Time Machine 2,1
overview,30,30,Time travel comedy.,1
poster_path,29,29,/poster1.jpg,1
production_companies,27,21,"[{""name"": ""Paramount Pictures""}]",4
production_countries,30,5,"[{""iso_3166_1"": ""US""}]",18
release_date,30,30,2/20/15,1
spoken_languages,30,8,"[{""name"": ""English""}]",18
status,30,2,Released,29
tagline,25,25,The Laws of Space and Time,1
title,30,30,Hot Tub Time Machine 2,1
Keywords,29,29,time travel,1
cast,30,27,"[{""name"": ""Aamir Khan""}]",3
crew,30,26,"[{""name"": ""Christopher Nolan"", ""job"": ""Directo...",3

- column names

In [10]:
df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

- check the duplicate rows

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
#df.drop_duplicates()    # if duplicate exist we have to remove with this function

- check  Null values

In [13]:
df.isnull()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
13,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
23,False,False,False,True,True,False,False,False,False,False,...,False,True,False,False,True,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [14]:
df.isnull().sum()

id                        0
belongs_to_collection     0
budget                    0
genres                    1
homepage                 21
imdb_id                   0
original_language         0
original_title            0
overview                  0
popularity                0
poster_path               1
production_companies      3
production_countries      0
release_date              0
runtime                   1
spoken_languages          0
status                    0
tagline                   5
title                     0
Keywords                  1
cast                      0
crew                      0
revenue                   0
dtype: int64

In [15]:
df.isnull().sum()/df.shape[0]*100

id                        0.000000
belongs_to_collection     0.000000
budget                    0.000000
genres                    3.333333
homepage                 70.000000
imdb_id                   0.000000
original_language         0.000000
original_title            0.000000
overview                  0.000000
popularity                0.000000
poster_path               3.333333
production_companies     10.000000
production_countries      0.000000
release_date              0.000000
runtime                   3.333333
spoken_languages          0.000000
status                    0.000000
tagline                  16.666667
title                     0.000000
Keywords                  3.333333
cast                      0.000000
crew                      0.000000
revenue                   0.000000
dtype: float64

In [16]:
df.drop(columns=["homepage"],inplace=True)    # if the missing value are morethan or equal to 25% we have to remove

In [17]:
df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'imdb_id',
       'original_language', 'original_title', 'overview', 'popularity',
       'poster_path', 'production_companies', 'production_countries',
       'release_date', 'runtime', 'spoken_languages', 'status', 'tagline',
       'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [18]:
df.head(1)

,id,belongs_to_collection,budget,genres,imdb_id,original_language,original_title,overview,popularity,poster_path,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,Hot Tub Time Machine 2,14000000,"[{""name"": ""Comedy""}]",tt2637294,en,Hot Tub Time Machine 2,Time travel comedy.,6.575393,/poster1.jpg,...,2/20/15,93.0,"[{""name"": ""English""}]",Released,The Laws of Space and Time,Hot Tub Time Machine 2,time travel,"[{""name"": ""Rob Corddry""}]","[{""name"": ""Steve Pink"", ""job"": ""Director""}]",12314651

# - filling missing values

In [ ]:
df.genres  =   df.genres.fillna(df.genres.mode()[0])

In [ ]:
df["poster_path"]  =   df["poster_path"].fillna(df["poster_path"].mode()[0])

In [22]:
df.production_companies=df.production_companies.fillna(df.production_companies.mode()[0])

In [23]:
df.runtime=df.runtime.fillna(df.runtime.mean())

In [24]:
df.tagline=df.tagline.fillna(df.tagline.mode()[0])

In [25]:
df.Keywords=df.Keywords.fillna(df.Keywords.mode()[0])

In [26]:
df.isnull().sum()

id                       0
belongs_to_collection    0
budget                   0
genres                   0
imdb_id                  0
original_language        0
original_title           0
overview                 0
popularity               0
poster_path              0
production_companies     0
production_countries     0
release_date             0
runtime                  0
spoken_languages         0
status                   0
tagline                  0
title                    0
Keywords                 0
cast                     0
crew                     0
revenue                  0
dtype: int64

# - fix the datatype issue

In [30]:
df.dtypes

id                         int64
belongs_to_collection     object
budget                     int64
genres                    object
imdb_id                   object
original_language         object
original_title            object
overview                  object
popularity               float64
poster_path               object
production_companies      object
production_countries      object
release_date              object
runtime                  float64
spoken_languages          object
status                    object
tagline                   object
title                     object
Keywords                  object
cast                      object
crew                      object
revenue                    int64
dtype: object

In [28]:
df.imdb_id.value_counts()

imdb_id
tt2637294     1
tt0368933     1
tt3783958     1
tt7286456     1
tt4849438     1
tt8178634     1
tt15327088    1
tt9000002     1
tt9000001     1
tt0068646     1
tt0245429     1
tt0120338     1
tt4154796     1
tt5074352     1
tt0816692     1
tt1600195     1
tt0343135     1
tt0116908     1
tt2364975     1
tt0109403     1
tt0105327     1
tt0362227     1
tt6751668     1
tt1187043     1
tt0468569     1
tt1375666     1
tt1380152     1
tt1821480     1
tt2582802     1
tt0112870     1
Name: count, dtype: int64

In [31]:
# remove the text in  IMDB_ID

df['imdb_id'] = df['imdb_id'].str.split().str[0].str.replace('tt', '', regex=False)

In [32]:
df['imdb_id'].value_counts()

imdb_id
2637294     1
0368933     1
3783958     1
7286456     1
4849438     1
8178634     1
15327088    1
9000002     1
9000001     1
0068646     1
0245429     1
0120338     1
4154796     1
5074352     1
0816692     1
1600195     1
0343135     1
0116908     1
2364975     1
0109403     1
0105327     1
0362227     1
6751668     1
1187043     1
0468569     1
1375666     1
1380152     1
1821480     1
2582802     1
0112870     1
Name: count, dtype: int64

In [33]:
# change the datatype

df['imdb_id']=df['imdb_id'].astype("int64")

In [34]:
df.dtypes

id                         int64
belongs_to_collection     object
budget                     int64
genres                    object
imdb_id                    int64
original_language         object
original_title            object
overview                  object
popularity               float64
poster_path               object
production_companies      object
production_countries      object
release_date              object
runtime                  float64
spoken_languages          object
status                    object
tagline                   object
title                     object
Keywords                  object
cast                      object
crew                      object
revenue                    int64
dtype: object

In [35]:
df.release_date.value_counts()

release_date
2/20/15     1
8/6/04      1
12/25/16    1
10/4/19     1
4/28/17     1
3/25/22     1
9/30/22     1
10/10/18    1
8/15/20     1
3/24/72     1
7/20/01     1
12/19/97    1
4/26/19     1
12/23/16    1
11/7/14     1
9/22/11     1
1/16/04     1
10/11/96    1
3/28/13     1
4/22/94     1
9/18/92     1
6/17/04     1
5/30/19     1
12/25/09    1
7/18/08     1
7/16/10     1
2/5/09      1
3/9/12      1
10/10/14    1
10/20/95    1
Name: count, dtype: int64

In [36]:
df.release_date=pd.to_datetime(df.release_date,errors="coerce")

C:\Users\LakshmanAIMLHYD\AppData\Local\Temp\ipykernel_13612\3125924932.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df.release_date=pd.to_datetime(df.release_date,errors="coerce")

In [37]:
df.dtypes

id                                int64
belongs_to_collection            object
budget                            int64
genres                           object
imdb_id                           int64
original_language                object
original_title                   object
overview                         object
popularity                      float64
poster_path                      object
production_companies             object
production_countries             object
release_date             datetime64[ns]
runtime                         float64
spoken_languages                 object
status                           object
tagline                          object
title                            object
Keywords                         object
cast                             object
crew                             object
revenue                           int64
dtype: object

In [ ]:
df.year=df.release_date.dt.year

C:\Users\LakshmanAIMLHYD\AppData\Local\Temp\ipykernel_13612\3651849922.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.year=df.release_date.dt.year

In [39]:
df.month=df.release_date.dt.month

C:\Users\LakshmanAIMLHYD\AppData\Local\Temp\ipykernel_13612\2720067362.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.month=df.release_date.dt.month

In [40]:
df.day=df.release_date.dt.day

C:\Users\LakshmanAIMLHYD\AppData\Local\Temp\ipykernel_13612\4083887189.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  df.day=df.release_date.dt.day

In [41]:
df.head(1)

,id,belongs_to_collection,budget,genres,imdb_id,original_language,original_title,overview,popularity,poster_path,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,Hot Tub Time Machine 2,14000000,"[{""name"": ""Comedy""}]",2637294,en,Hot Tub Time Machine 2,Time travel comedy.,6.575393,/poster1.jpg,...,2015-02-20,93.0,"[{""name"": ""English""}]",Released,The Laws of Space and Time,Hot Tub Time Machine 2,time travel,"[{""name"": ""Rob Corddry""}]","[{""name"": ""Steve Pink"", ""job"": ""Director""}]",12314651

# <u>**Indexing and Slicing**</u>

In [9]:
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,Hot Tub Time Machine 2,14000000,"[{""name"": ""Comedy""}]",NaN,tt2637294,en,Hot Tub Time Machine 2,Time travel comedy.,6.575393,...,2/20/15,93.0,"[{""name"": ""English""}]",Released,The Laws of Space and Time,Hot Tub Time Machine 2,time travel,"[{""name"": ""Rob Corddry""}]","[{""name"": ""Steve Pink"", ""job"": ""Director""}]",12314651
1,2,The Princess Diaries 2: Royal Engagement,40000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,A princess prepares for marriage.,8.248895,...,8/6/04,113.0,"[{""name"": ""English""}]",Released,It can take a lifetime to find true love.,The Princess Diaries 2: Royal Engagement,princess|royalty,"[{""name"": ""Anne Hathaway""}]","[{""name"": ""Garry Marshall"", ""job"": ""Director""}]",95149435
2,3,Whiplash,3300000,"[{""name"": ""Drama""}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,A young drummer faces a ruthless instructor.,64.299990,...,10/10/14,105.0,"[{""name"": ""English""}]",Released,The road to greatness can take you to the edge.,Whiplash,jazz|music,"[{""name"": ""Miles Teller""}]","[{""name"": ""Damien Chazelle"", ""job"": ""Director""}]",13092000
3,4,Kahaani,1200000,"[{""name"": ""Thriller""}, {""name"": ""Drama""}]",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,A woman searches for her missing husband in Ko...,3.174936,...,3/9/12,122.0,"[{""name"": ""English|Hindi""}]",Released,NaN,Kahaani,mystery|kolkata,"[{""name"": ""Vidya Balan""}]","[{""name"": ""Sujoy Ghosh"", ""job"": ""Director""}]",16000000
4,5,Marine Boy,0,"[{""name"": ""Action""}, {""name"": ""Thriller""}]",NaN,tt1380152,ko,Marine Boy,A former swimmer becomes involved in crime.,1.148070,...,2/5/09,118.0,"[{""name"": ""Korean""}]",Released,NaN,Marine Boy,NaN,"[{""name"": ""Kim Kang-woo""}]","[{""name"": ""Yoon Jong-chan"", ""job"": ""Director""}]",3923970

## **<code>iloc</code>** gets rows (or columns) at particular positions in the index (so it only takes integers).

In [10]:
# Let us get a subset which consists of first 8 rows and first 4 columns
df.iloc[:,-3:]

,cast,crew,revenue
0,"[{""name"": ""Rob Corddry""}]","[{""name"": ""Steve Pink"", ""job"": ""Director""}]",12314651
1,"[{""name"": ""Anne Hathaway""}]","[{""name"": ""Garry Marshall"", ""job"": ""Director""}]",95149435
2,"[{""name"": ""Miles Teller""}]","[{""name"": ""Damien Chazelle"", ""job"": ""Director""}]",13092000
3,"[{""name"": ""Vidya Balan""}]","[{""name"": ""Sujoy Ghosh"", ""job"": ""Director""}]",16000000
4,"[{""name"": ""Kim Kang-woo""}]","[{""name"": ""Yoon Jong-chan"", ""job"": ""Director""}]",3923970
5,"[{""name"": ""Leonardo DiCaprio""}]","[{""name"": ""Christopher Nolan"", ""job"": ""Directo...",839000000
6,"[{""name"": ""Christian Bale""}]","[{""name"": ""Christopher Nolan"", ""job"": ""Directo...",1004558444
7,"[{""name"": ""Aamir Khan""}]","[{""name"": ""Rajkumar Hirani"", ""job"": ""Director""}]",2000000000
8,"[{""name"": ""Song Kang-ho""}]","[{""name"": ""Bong Joon Ho"", ""job"": ""Director""}]",258000000
9,"[{""name"": ""Tom Hanks""}]","[{""name"": ""Steven Spielberg"", ""job"": ""Director""}]",219417255
10,"[{""name"": ""Brendan Fraser""}]","[{""name"": ""Robert Mandel"", ""job"": ""Director""}]",14715067
11,"[{""name"": ""Tom Berenger""}]","[{""name"": ""Dennis Hopper"", ""job"": ""Director""}]",1596687
12,"[{""name"": ""Mira Barkhammar""}]","[{""name"": ""Lukas Moodysson"", ""job"": ""Director""}]",180590
13,"[{""name"": ""Geena Davis""}]","[{""name"": ""Renny Harlin"", ""job"": ""Director""}]",89456761
14,"[{""name"": ""Ben Stiller""}]","[{""name"": ""John Hamburg"", ""job"": ""Director""}]",171963386
15,"[{""name"": ""Taylor Lautner""}]","[{""name"": ""John Singleton"", ""job"": ""Director""}]",82087155
16,"[{""name"": ""Matthew McConaughey""}]","[{""name"": ""Christopher Nolan"", ""job"": ""Directo...",701729206
17,"[{""name"": ""Aamir Khan""}]","[{""name"": ""Nitesh Tiwari"", ""job"": ""Director""}]",310000000
18,"[{""name"": ""Robert Downey Jr.""}]","[{""name"": ""Anthony Russo"", ""job"": ""Director""}]",2797501328
19,"[{""name"": ""Leonardo DiCaprio""}]","[{""name"": ""James Cameron"", ""job"": ""Director""}]",2264743305
20,"[{""name"": ""Rumi Hiiragi""}]","[{""name"": ""Hayao Miyazaki"", ""job"": ""Director""}]",395800000
21,"[{""name"": ""Marlon Brando""}]","[{""name"": ""Francis Ford Coppola"", ""job"": ""Dire...",250000000
22,"[{""name"": ""Aamir Khan""}]","[{""name"": ""Demo Director"", ""job"": ""Director""}]",0
23,"[{""name"": ""Unknown""}]","[{""name"": ""Unknown"", ""job"": ""Director""}]",45000000
24,"[{""name"": ""Rishab Shetty""}]","[{""name"": ""Rishab Shetty"", ""job"": ""Director""}]",400000000
25,"[{""name"": ""N. T. Rama Rao Jr.""}]","[{""name"": ""S. S. Rajamouli"", ""job"": ""Director""}]",1200000000
26,"[{""name"": ""Prabhas""}]","[{""name"": ""S. S. Rajamouli"", ""job"": ""Director""}]",1810000000
27,"[{""name"": ""Joaquin Phoenix""}]","[{""name"": ""Todd Phillips"", ""job"": ""Director""}]",1074251311
28,"[{""name"": ""Ryan Gosling""}]","[{""name"": ""Damien Chazelle"", ""job"": ""Director""}]",472000000
29,"[{""name"": ""Shah Rukh Khan""}]","[{""name"": ""Aditya Chopra"", ""job"": ""Director""}]",120000000

## **<code>loc</code>** gets rows (or columns) with particular labels from the index.

In [11]:
# Now let us subset our dataframe in which we want to have first 8 rows identified with their rows labels and some named columns
df.loc[50:60,['budget','genres','runtime']]

Empty DataFrame
Columns: [budget, genres, runtime]
Index: []

In [12]:
df.loc[:,['budget','genres','runtime']]

       budget                                             genres  runtime
0    14000000                               [{"name": "Comedy"}]     93.0
1    40000000            [{"name": "Comedy"}, {"name": "Drama"}]    113.0
2     3300000                                [{"name": "Drama"}]    105.0
3     1200000          [{"name": "Thriller"}, {"name": "Drama"}]    122.0
4           0         [{"name": "Action"}, {"name": "Thriller"}]    118.0
5   160000000           [{"name": "Action"}, {"name": "Sci-Fi"}]    148.0
6   185000000  [{"name": "Action"}, {"name": "Crime"}, {"name...    152.0
7   550000000            [{"name": "Comedy"}, {"name": "Drama"}]    170.0
8    11400000          [{"name": "Drama"}, {"name": "Thriller"}]    132.0
9    60000000            [{"name": "Comedy"}, {"name": "Drama"}]    128.0
10          0                                [{"name": "Drama"}]    106.0
11          0          [{"name": "Comedy"}, {"name": "Romance"}]    102.0
12          0             [{"name": "Drama"}, {"name": "Music"}]    102.0
13   65000000            [{"name": "Crime"}, {"name": "Action"}]    120.0
14   42000000          [{"name": "Comedy"}, {"name": "Romance"}]     90.0
15   35000000         [{"name": "Thriller"}, {"name": "Action"}]    106.0
16  165000000  [{"name": "Adventure"}, {"name": "Drama"}, {"n...    169.0
17   70000000             [{"name": "Drama"}, {"name": "Sport"}]    161.0
18  356000000  [{"name": "Action"}, {"name": "Adventure"}, {"...    181.0
19  200000000           [{"name": "Drama"}, {"name": "Romance"}]    194.0
20   19000000       [{"name": "Animation"}, {"name": "Fantasy"}]    125.0
21    6000000             [{"name": "Crime"}, {"name": "Drama"}]    175.0
22   80000000            [{"name": "Comedy"}, {"name": "Drama"}]      0.0
23   25000000                                                NaN      NaN
24   16000000            [{"name": "Action"}, {"name": "Drama"}]    148.0
25  550000000            [{"name": "Action"}, {"name": "Drama"}]    187.0
26  250000000            [{"name": "Action"}, {"name": "Drama"}]    168.0
27   55000000             [{"name": "Crime"}, {"name": "Drama"}]    122.0
28   30000000  [{"name": "Comedy"}, {"name": "Drama"}, {"name...    128.0
29   40000000           [{"name": "Drama"}, {"name": "Romance"}]    181.0

In [13]:
df[0:10]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,Hot Tub Time Machine 2,14000000,"[{""name"": ""Comedy""}]",NaN,tt2637294,en,Hot Tub Time Machine 2,Time travel comedy.,6.575393,...,2/20/15,93.0,"[{""name"": ""English""}]",Released,The Laws of Space and Time,Hot Tub Time Machine 2,time travel,"[{""name"": ""Rob Corddry""}]","[{""name"": ""Steve Pink"", ""job"": ""Director""}]",12314651
1,2,The Princess Diaries 2: Royal Engagement,40000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,A princess prepares for marriage.,8.248895,...,8/6/04,113.0,"[{""name"": ""English""}]",Released,It can take a lifetime to find true love.,The Princess Diaries 2: Royal Engagement,princess|royalty,"[{""name"": ""Anne Hathaway""}]","[{""name"": ""Garry Marshall"", ""job"": ""Director""}]",95149435
2,3,Whiplash,3300000,"[{""name"": ""Drama""}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,A young drummer faces a ruthless instructor.,64.299990,...,10/10/14,105.0,"[{""name"": ""English""}]",Released,The road to greatness can take you to the edge.,Whiplash,jazz|music,"[{""name"": ""Miles Teller""}]","[{""name"": ""Damien Chazelle"", ""job"": ""Director""}]",13092000
3,4,Kahaani,1200000,"[{""name"": ""Thriller""}, {""name"": ""Drama""}]",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,A woman searches for her missing husband in Ko...,3.174936,...,3/9/12,122.0,"[{""name"": ""English|Hindi""}]",Released,NaN,Kahaani,mystery|kolkata,"[{""name"": ""Vidya Balan""}]","[{""name"": ""Sujoy Ghosh"", ""job"": ""Director""}]",16000000
4,5,Marine Boy,0,"[{""name"": ""Action""}, {""name"": ""Thriller""}]",NaN,tt1380152,ko,Marine Boy,A former swimmer becomes involved in crime.,1.148070,...,2/5/09,118.0,"[{""name"": ""Korean""}]",Released,NaN,Marine Boy,NaN,"[{""name"": ""Kim Kang-woo""}]","[{""name"": ""Yoon Jong-chan"", ""job"": ""Director""}]",3923970
5,6,Inception,160000000,"[{""name"": ""Action""}, {""name"": ""Sci-Fi""}]",https://example.com/inception,tt1375666,en,Inception,A thief enters dreams to steal secrets.,82.500000,...,7/16/10,148.0,"[{""name"": ""English""}]",Released,Your mind is the scene of the crime.,Inception,dream|heist,"[{""name"": ""Leonardo DiCaprio""}]","[{""name"": ""Christopher Nolan"", ""job"": ""Directo...",839000000
6,7,The Dark Knight,185000000,"[{""name"": ""Action""}, {""name"": ""Crime""}, {""name...",NaN,tt0468569,en,The Dark Knight,Batman faces the Joker.,90.100000,...,7/18/08,152.0,"[{""name"": ""English""}]",Released,Why so serious?,The Dark Knight,joker|batman,"[{""name"": ""Christian Bale""}]","[{""name"": ""Christopher Nolan"", ""job"": ""Directo...",1004558444
7,8,3 Idiots,550000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",https://example.com/3idiots,tt1187043,hi,3 Idiots,Three friends navigate college and life.,25.300000,...,12/25/09,170.0,"[{""name"": ""Hindi""}]",Released,All is well.,3 Idiots,college|friendship,"[{""name"": ""Aamir Khan""}]","[{""name"": ""Rajkumar Hirani"", ""job"": ""Director""}]",2000000000
8,9,Parasite,11400000,"[{""name"": ""Drama""}, {""name"": ""Thriller""}]",NaN,tt6751668,ko,Parasite,Two families become entangled in a strange sit...,55.700000,...,5/30/19,132.0,"[{""name"": ""Korean""}]",Released,Act like you own the place.,Parasite,family|class,"[{""name"": ""Song Kang-ho""}]","[{""name"": ""Bong Joon Ho"", ""job"": ""Director""}]",258000000
9,10,The Terminal,60000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",http://www.theterminal-themovie.com/,tt0362227,en,The Terminal,A man becomes stranded in an airport.,14.092373,...,6/17/04,128.0,"[{""name"": ""English""}]",Released,Life is waiting.,The Terminal,airport|new york,"[{""name"": ""Tom Hanks""}]","[{""name"": ""Steven Spielberg"", ""job"": ""Director""}]",219417255

In [14]:
df[['original_language','release_date','cast']]

   original_language release_date                               cast
0                 en      2/20/15          [{"name": "Rob Corddry"}]
1                 en       8/6/04        [{"name": "Anne Hathaway"}]
2                 en     10/10/14         [{"name": "Miles Teller"}]
3                 hi       3/9/12          [{"name": "Vidya Balan"}]
4                 ko       2/5/09         [{"name": "Kim Kang-woo"}]
5                 en      7/16/10    [{"name": "Leonardo DiCaprio"}]
6                 en      7/18/08       [{"name": "Christian Bale"}]
7                 hi     12/25/09           [{"name": "Aamir Khan"}]
8                 ko      5/30/19         [{"name": "Song Kang-ho"}]
9                 en      6/17/04            [{"name": "Tom Hanks"}]
10                en      9/18/92       [{"name": "Brendan Fraser"}]
11                en      4/22/94         [{"name": "Tom Berenger"}]
12                sv      3/28/13      [{"name": "Mira Barkhammar"}]
13                en     10/11/96          [{"name": "Geena Davis"}]
14                en      1/16/04          [{"name": "Ben Stiller"}]
15                en      9/22/11       [{"name": "Taylor Lautner"}]
16                en      11/7/14  [{"name": "Matthew McConaughey"}]
17                hi     12/23/16           [{"name": "Aamir Khan"}]
18                en      4/26/19    [{"name": "Robert Downey Jr."}]
19                en     12/19/97    [{"name": "Leonardo DiCaprio"}]
20                ja      7/20/01         [{"name": "Rumi Hiiragi"}]
21                en      3/24/72        [{"name": "Marlon Brando"}]
22                hi      8/15/20           [{"name": "Aamir Khan"}]
23                en     10/10/18              [{"name": "Unknown"}]
24                kn      9/30/22        [{"name": "Rishab Shetty"}]
25                te      3/25/22   [{"name": "N. T. Rama Rao Jr."}]
26                te      4/28/17              [{"name": "Prabhas"}]
27                en      10/4/19      [{"name": "Joaquin Phoenix"}]
28                en     12/25/16         [{"name": "Ryan Gosling"}]
29                hi     10/20/95       [{"name": "Shah Rukh Khan"}]

In [15]:
df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='str')

## <b>In fact we can also perform boolean indexing on our dataframe</b>

In [16]:
df['original_language'] == 'en'

0      True
1      True
2      True
3     False
4     False
5      True
6      True
7     False
8     False
9      True
10     True
11     True
12    False
13     True
14     True
15     True
16     True
17    False
18     True
19     True
20    False
21     True
22    False
23     True
24    False
25    False
26    False
27     True
28     True
29    False
Name: original_language, dtype: bool

In [17]:
# Boolean Indexing
english_movies = df[df['original_language'] == 'en']
english_movies.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,Hot Tub Time Machine 2,14000000,"[{""name"": ""Comedy""}]",NaN,tt2637294,en,Hot Tub Time Machine 2,Time travel comedy.,6.575393,...,2/20/15,93.0,"[{""name"": ""English""}]",Released,The Laws of Space and Time,Hot Tub Time Machine 2,time travel,"[{""name"": ""Rob Corddry""}]","[{""name"": ""Steve Pink"", ""job"": ""Director""}]",12314651
1,2,The Princess Diaries 2: Royal Engagement,40000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,A princess prepares for marriage.,8.248895,...,8/6/04,113.0,"[{""name"": ""English""}]",Released,It can take a lifetime to find true love.,The Princess Diaries 2: Royal Engagement,princess|royalty,"[{""name"": ""Anne Hathaway""}]","[{""name"": ""Garry Marshall"", ""job"": ""Director""}]",95149435
2,3,Whiplash,3300000,"[{""name"": ""Drama""}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,A young drummer faces a ruthless instructor.,64.299990,...,10/10/14,105.0,"[{""name"": ""English""}]",Released,The road to greatness can take you to the edge.,Whiplash,jazz|music,"[{""name"": ""Miles Teller""}]","[{""name"": ""Damien Chazelle"", ""job"": ""Director""}]",13092000
5,6,Inception,160000000,"[{""name"": ""Action""}, {""name"": ""Sci-Fi""}]",https://example.com/inception,tt1375666,en,Inception,A thief enters dreams to steal secrets.,82.500000,...,7/16/10,148.0,"[{""name"": ""English""}]",Released,Your mind is the scene of the crime.,Inception,dream|heist,"[{""name"": ""Leonardo DiCaprio""}]","[{""name"": ""Christopher Nolan"", ""job"": ""Directo...",839000000
6,7,The Dark Knight,185000000,"[{""name"": ""Action""}, {""name"": ""Crime""}, {""name...",NaN,tt0468569,en,The Dark Knight,Batman faces the Joker.,90.100000,...,7/18/08,152.0,"[{""name"": ""English""}]",Released,Why so serious?,The Dark Knight,joker|batman,"[{""name"": ""Christian Bale""}]","[{""name"": ""Christopher Nolan"", ""job"": ""Directo...",1004558444

In [18]:
english_movies.shape

(18, 23)

In [19]:
non_english_movies = df[df['original_language'] != 'en']
non_english_movies.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
3,4,Kahaani,1200000,"[{""name"": ""Thriller""}, {""name"": ""Drama""}]",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,A woman searches for her missing husband in Ko...,3.174936,...,3/9/12,122.0,"[{""name"": ""English|Hindi""}]",Released,NaN,Kahaani,mystery|kolkata,"[{""name"": ""Vidya Balan""}]","[{""name"": ""Sujoy Ghosh"", ""job"": ""Director""}]",16000000
4,5,Marine Boy,0,"[{""name"": ""Action""}, {""name"": ""Thriller""}]",NaN,tt1380152,ko,Marine Boy,A former swimmer becomes involved in crime.,1.148070,...,2/5/09,118.0,"[{""name"": ""Korean""}]",Released,NaN,Marine Boy,NaN,"[{""name"": ""Kim Kang-woo""}]","[{""name"": ""Yoon Jong-chan"", ""job"": ""Director""}]",3923970
7,8,3 Idiots,550000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",https://example.com/3idiots,tt1187043,hi,3 Idiots,Three friends navigate college and life.,25.300000,...,12/25/09,170.0,"[{""name"": ""Hindi""}]",Released,All is well.,3 Idiots,college|friendship,"[{""name"": ""Aamir Khan""}]","[{""name"": ""Rajkumar Hirani"", ""job"": ""Director""}]",2000000000
8,9,Parasite,11400000,"[{""name"": ""Drama""}, {""name"": ""Thriller""}]",NaN,tt6751668,ko,Parasite,Two families become entangled in a strange sit...,55.700000,...,5/30/19,132.0,"[{""name"": ""Korean""}]",Released,Act like you own the place.,Parasite,family|class,"[{""name"": ""Song Kang-ho""}]","[{""name"": ""Bong Joon Ho"", ""job"": ""Director""}]",258000000
12,13,We Are the Best!,0,"[{""name"": ""Drama""}, {""name"": ""Music""}]",NaN,tt2364975,sv,We Are the Best!,Three girls form a punk band.,3.727996,...,3/28/13,102.0,"[{""name"": ""Swedish""}]",Released,NaN,We Are the Best!,sweden|punk,"[{""name"": ""Mira Barkhammar""}]","[{""name"": ""Lukas Moodysson"", ""job"": ""Director""}]",180590

In [20]:
long_movies = df[df['runtime'] > 120]
long_movies[['title','cast']]

                          title                               cast
3                       Kahaani          [{"name": "Vidya Balan"}]
5                     Inception    [{"name": "Leonardo DiCaprio"}]
6               The Dark Knight       [{"name": "Christian Bale"}]
7                      3 Idiots           [{"name": "Aamir Khan"}]
8                      Parasite         [{"name": "Song Kang-ho"}]
9                  The Terminal            [{"name": "Tom Hanks"}]
16                 Interstellar  [{"name": "Matthew McConaughey"}]
17                       Dangal           [{"name": "Aamir Khan"}]
18            Avengers: Endgame    [{"name": "Robert Downey Jr."}]
19                      Titanic    [{"name": "Leonardo DiCaprio"}]
20                Spirited Away         [{"name": "Rumi Hiiragi"}]
21                The Godfather        [{"name": "Marlon Brando"}]
24                      Kantara        [{"name": "Rishab Shetty"}]
25                          RRR   [{"name": "N. T. Rama Rao Jr."}]
26  Baahubali 2: The Conclusion              [{"name": "Prabhas"}]
27                        Joker      [{"name": "Joaquin Phoenix"}]
28                   La La Land         [{"name": "Ryan Gosling"}]
29  Dilwale Dulhania Le Jayenge       [{"name": "Shah Rukh Khan"}]

## Infact we can match conditions for mutliple columns

In [21]:
long_movies = df[df['runtime'] > 120]

In [22]:
long_movies.tail()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
25,26,RRR,550000000,"[{""name"": ""Action""}, {""name"": ""Drama""}]",NaN,tt8178634,te,RRR,Two revolutionaries form an unlikely friendship.,60.3,...,3/25/22,187.0,"[{""name"": ""Telugu""}]",Released,Rise. Roar. Revolt.,RRR,friendship|revolution,"[{""name"": ""N. T. Rama Rao Jr.""}]","[{""name"": ""S. S. Rajamouli"", ""job"": ""Director""}]",1200000000
26,27,Bahubali 2: The Conclusion,250000000,"[{""name"": ""Action""}, {""name"": ""Drama""}]",NaN,tt4849438,te,Baahubali 2: The Conclusion,A kingdom seeks answers and revenge.,52.9,...,4/28/17,168.0,"[{""name"": ""Telugu""}]",Released,Why did Kattappa kill Baahubali?,Baahubali 2: The Conclusion,kingdom|war,"[{""name"": ""Prabhas""}]","[{""name"": ""S. S. Rajamouli"", ""job"": ""Director""}]",1810000000
27,28,Joker,55000000,"[{""name"": ""Crime""}, {""name"": ""Drama""}]",NaN,tt7286456,en,Joker,A failed comedian descends into chaos.,70.9,...,10/4/19,122.0,"[{""name"": ""English""}]",Released,Put on a happy face.,Joker,joker|crime,"[{""name"": ""Joaquin Phoenix""}]","[{""name"": ""Todd Phillips"", ""job"": ""Director""}]",1074251311
28,29,La La Land,30000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}, {""name...",NaN,tt3783958,en,La La Land,A musician and actress pursue dreams in Los An...,35.8,...,12/25/16,128.0,"[{""name"": ""English""}]",Released,Here's to the fools who dream.,La La Land,music|los angeles,"[{""name"": ""Ryan Gosling""}]","[{""name"": ""Damien Chazelle"", ""job"": ""Director""}]",472000000
29,30,Dilwale Dulhania Le Jayenge,40000000,"[{""name"": ""Drama""}, {""name"": ""Romance""}]",NaN,tt0112870,hi,Dilwale Dulhania Le Jayenge,A young couple challenges family expectations.,20.6,...,10/20/95,181.0,"[{""name"": ""Hindi""}]",Released,Come... Fall in love.,Dilwale Dulhania Le Jayenge,romance|family,"[{""name"": ""Shah Rukh Khan""}]","[{""name"": ""Aditya Chopra"", ""job"": ""Director""}]",120000000

In [23]:
(df['original_language']=='en') & (df['runtime'] > 120)

0     False
1     False
2     False
3     False
4     False
5      True
6      True
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16     True
17    False
18     True
19     True
20    False
21     True
22    False
23    False
24    False
25    False
26    False
27     True
28     True
29    False
dtype: bool

In [24]:
long_english_movies = df[(df['original_language']=='en') & (df['runtime'] > 120)]
long_english_movies.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
5,6,Inception,160000000,"[{""name"": ""Action""}, {""name"": ""Sci-Fi""}]",https://example.com/inception,tt1375666,en,Inception,A thief enters dreams to steal secrets.,82.500000,...,7/16/10,148.0,"[{""name"": ""English""}]",Released,Your mind is the scene of the crime.,Inception,dream|heist,"[{""name"": ""Leonardo DiCaprio""}]","[{""name"": ""Christopher Nolan"", ""job"": ""Directo...",839000000
6,7,The Dark Knight,185000000,"[{""name"": ""Action""}, {""name"": ""Crime""}, {""name...",NaN,tt0468569,en,The Dark Knight,Batman faces the Joker.,90.100000,...,7/18/08,152.0,"[{""name"": ""English""}]",Released,Why so serious?,The Dark Knight,joker|batman,"[{""name"": ""Christian Bale""}]","[{""name"": ""Christopher Nolan"", ""job"": ""Directo...",1004558444
9,10,The Terminal,60000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",http://www.theterminal-themovie.com/,tt0362227,en,The Terminal,A man becomes stranded in an airport.,14.092373,...,6/17/04,128.0,"[{""name"": ""English""}]",Released,Life is waiting.,The Terminal,airport|new york,"[{""name"": ""Tom Hanks""}]","[{""name"": ""Steven Spielberg"", ""job"": ""Director""}]",219417255
16,17,Interstellar,165000000,"[{""name"": ""Adventure""}, {""name"": ""Drama""}, {""n...",NaN,tt0816692,en,Interstellar,Explorers travel through a wormhole in space.,75.000000,...,11/7/14,169.0,"[{""name"": ""English""}]",Released,Mankind was born on Earth. It was never meant ...,Interstellar,space|wormhole,"[{""name"": ""Matthew McConaughey""}]","[{""name"": ""Christopher Nolan"", ""job"": ""Directo...",701729206
18,19,Avengers: Endgame,356000000,"[{""name"": ""Action""}, {""name"": ""Adventure""}, {""...",NaN,tt4154796,en,Avengers: Endgame,Heroes attempt to reverse a devastating loss.,88.200000,...,4/26/19,181.0,"[{""name"": ""English""}]",Released,Avenge the fallen.,Avengers: Endgame,superhero|marvel,"[{""name"": ""Robert Downey Jr.""}]","[{""name"": ""Anthony Russo"", ""job"": ""Director""}]",2797501328

In [25]:
long_english_movies.shape

(9, 23)

# <u>**Next let us see how we can manipulate columns**</u>

In [26]:
df.shape

(30, 23)

## **Let's say if you wanted a new column whose values were half the movie runtime**

In [27]:
df['runtime']

0      93.0
1     113.0
2     105.0
3     122.0
4     118.0
5     148.0
6     152.0
7     170.0
8     132.0
9     128.0
10    106.0
11    102.0
12    102.0
13    120.0
14     90.0
15    106.0
16    169.0
17    161.0
18    181.0
19    194.0
20    125.0
21    175.0
22      0.0
23      NaN
24    148.0
25    187.0
26    168.0
27    122.0
28    128.0
29    181.0
Name: runtime, dtype: float64

In [28]:
# Add new column which is just half the runtime
df['half_runtime'] = df['runtime'] * 0.5

In [29]:
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,half_runtime
0,1,Hot Tub Time Machine 2,14000000,"[{""name"": ""Comedy""}]",NaN,tt2637294,en,Hot Tub Time Machine 2,Time travel comedy.,6.575393,...,93.0,"[{""name"": ""English""}]",Released,The Laws of Space and Time,Hot Tub Time Machine 2,time travel,"[{""name"": ""Rob Corddry""}]","[{""name"": ""Steve Pink"", ""job"": ""Director""}]",12314651,46.5
1,2,The Princess Diaries 2: Royal Engagement,40000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,A princess prepares for marriage.,8.248895,...,113.0,"[{""name"": ""English""}]",Released,It can take a lifetime to find true love.,The Princess Diaries 2: Royal Engagement,princess|royalty,"[{""name"": ""Anne Hathaway""}]","[{""name"": ""Garry Marshall"", ""job"": ""Director""}]",95149435,56.5
2,3,Whiplash,3300000,"[{""name"": ""Drama""}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,A young drummer faces a ruthless instructor.,64.299990,...,105.0,"[{""name"": ""English""}]",Released,The road to greatness can take you to the edge.,Whiplash,jazz|music,"[{""name"": ""Miles Teller""}]","[{""name"": ""Damien Chazelle"", ""job"": ""Director""}]",13092000,52.5
3,4,Kahaani,1200000,"[{""name"": ""Thriller""}, {""name"": ""Drama""}]",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,A woman searches for her missing husband in Ko...,3.174936,...,122.0,"[{""name"": ""English|Hindi""}]",Released,NaN,Kahaani,mystery|kolkata,"[{""name"": ""Vidya Balan""}]","[{""name"": ""Sujoy Ghosh"", ""job"": ""Director""}]",16000000,61.0
4,5,Marine Boy,0,"[{""name"": ""Action""}, {""name"": ""Thriller""}]",NaN,tt1380152,ko,Marine Boy,A former swimmer becomes involved in crime.,1.148070,...,118.0,"[{""name"": ""Korean""}]",Released,NaN,Marine Boy,NaN,"[{""name"": ""Kim Kang-woo""}]","[{""name"": ""Yoon Jong-chan"", ""job"": ""Director""}]",3923970,59.0

## We can also create a new column by adding two existing columns

In [30]:
# Creating another new column by subtracting/adding two existing columns
df['movie_profit'] = df['revenue'] - df['budget']

In [31]:
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,half_runtime,movie_profit
0,1,Hot Tub Time Machine 2,14000000,"[{""name"": ""Comedy""}]",NaN,tt2637294,en,Hot Tub Time Machine 2,Time travel comedy.,6.575393,...,"[{""name"": ""English""}]",Released,The Laws of Space and Time,Hot Tub Time Machine 2,time travel,"[{""name"": ""Rob Corddry""}]","[{""name"": ""Steve Pink"", ""job"": ""Director""}]",12314651,46.5,-1685349
1,2,The Princess Diaries 2: Royal Engagement,40000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,A princess prepares for marriage.,8.248895,...,"[{""name"": ""English""}]",Released,It can take a lifetime to find true love.,The Princess Diaries 2: Royal Engagement,princess|royalty,"[{""name"": ""Anne Hathaway""}]","[{""name"": ""Garry Marshall"", ""job"": ""Director""}]",95149435,56.5,55149435
2,3,Whiplash,3300000,"[{""name"": ""Drama""}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,A young drummer faces a ruthless instructor.,64.299990,...,"[{""name"": ""English""}]",Released,The road to greatness can take you to the edge.,Whiplash,jazz|music,"[{""name"": ""Miles Teller""}]","[{""name"": ""Damien Chazelle"", ""job"": ""Director""}]",13092000,52.5,9792000
3,4,Kahaani,1200000,"[{""name"": ""Thriller""}, {""name"": ""Drama""}]",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,A woman searches for her missing husband in Ko...,3.174936,...,"[{""name"": ""English|Hindi""}]",Released,NaN,Kahaani,mystery|kolkata,"[{""name"": ""Vidya Balan""}]","[{""name"": ""Sujoy Ghosh"", ""job"": ""Director""}]",16000000,61.0,14800000
4,5,Marine Boy,0,"[{""name"": ""Action""}, {""name"": ""Thriller""}]",NaN,tt1380152,ko,Marine Boy,A former swimmer becomes involved in crime.,1.148070,...,"[{""name"": ""Korean""}]",Released,NaN,Marine Boy,NaN,"[{""name"": ""Kim Kang-woo""}]","[{""name"": ""Yoon Jong-chan"", ""job"": ""Director""}]",3923970,59.0,3923970

## **Next, we can also drop some columns which we want to drop**

In [32]:
# Remove column
df.drop(['id'], axis = 1, inplace=True)

In [33]:
df.head()

,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,poster_path,...,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,half_runtime,movie_profit
0,Hot Tub Time Machine 2,14000000,"[{""name"": ""Comedy""}]",NaN,tt2637294,en,Hot Tub Time Machine 2,Time travel comedy.,6.575393,/poster1.jpg,...,"[{""name"": ""English""}]",Released,The Laws of Space and Time,Hot Tub Time Machine 2,time travel,"[{""name"": ""Rob Corddry""}]","[{""name"": ""Steve Pink"", ""job"": ""Director""}]",12314651,46.5,-1685349
1,The Princess Diaries 2: Royal Engagement,40000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,A princess prepares for marriage.,8.248895,/poster2.jpg,...,"[{""name"": ""English""}]",Released,It can take a lifetime to find true love.,The Princess Diaries 2: Royal Engagement,princess|royalty,"[{""name"": ""Anne Hathaway""}]","[{""name"": ""Garry Marshall"", ""job"": ""Director""}]",95149435,56.5,55149435
2,Whiplash,3300000,"[{""name"": ""Drama""}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,A young drummer faces a ruthless instructor.,64.299990,/poster3.jpg,...,"[{""name"": ""English""}]",Released,The road to greatness can take you to the edge.,Whiplash,jazz|music,"[{""name"": ""Miles Teller""}]","[{""name"": ""Damien Chazelle"", ""job"": ""Director""}]",13092000,52.5,9792000
3,Kahaani,1200000,"[{""name"": ""Thriller""}, {""name"": ""Drama""}]",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,A woman searches for her missing husband in Ko...,3.174936,/poster4.jpg,...,"[{""name"": ""English|Hindi""}]",Released,NaN,Kahaani,mystery|kolkata,"[{""name"": ""Vidya Balan""}]","[{""name"": ""Sujoy Ghosh"", ""job"": ""Director""}]",16000000,61.0,14800000
4,Marine Boy,0,"[{""name"": ""Action""}, {""name"": ""Thriller""}]",NaN,tt1380152,ko,Marine Boy,A former swimmer becomes involved in crime.,1.148070,/poster5.jpg,...,"[{""name"": ""Korean""}]",Released,NaN,Marine Boy,NaN,"[{""name"": ""Kim Kang-woo""}]","[{""name"": ""Yoon Jong-chan"", ""job"": ""Director""}]",3923970,59.0,3923970

In [34]:
df.describe()

,budget,popularity,runtime,revenue,half_runtime,movie_profit
count,3.000000e+01,30.000000,29.000000,3.000000e+01,29.000000,3.000000e+01
mean,1.009633e+08,39.042643,132.620690,5.554160e+08,66.310345,4.544527e+08
std,1.492895e+08,31.461444,40.063712,7.579332e+08,20.031856,6.478400e+08
min,0.000000e+00,1.148070,0.000000,0.000000e+00,0.000000,-8.000000e+07
25%,1.205000e+07,11.009082,106.000000,2.325000e+07,53.000000,1.610000e+07
50%,4.000000e+07,30.350000,128.000000,2.347086e+08,64.000000,1.997086e+08
75%,1.400000e+08,69.249998,168.000000,8.046823e+08,84.000000,6.216823e+08
max,5.500000e+08,95.300000,194.000000,2.797501e+09,97.000000,2.441501e+09

## You can drop  multiple columns at once too.

In [35]:
df.drop(['half_runtime','poster_path'],axis=1,inplace=True)

In [36]:
df.drop(['crew'], axis = 1, inplace=True)

In [37]:
df.head()

,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,production_companies,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,revenue,movie_profit
0,Hot Tub Time Machine 2,14000000,"[{""name"": ""Comedy""}]",NaN,tt2637294,en,Hot Tub Time Machine 2,Time travel comedy.,6.575393,"[{""name"": ""Paramount Pictures""}]",...,2/20/15,93.0,"[{""name"": ""English""}]",Released,The Laws of Space and Time,Hot Tub Time Machine 2,time travel,"[{""name"": ""Rob Corddry""}]",12314651,-1685349
1,The Princess Diaries 2: Royal Engagement,40000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,A princess prepares for marriage.,8.248895,"[{""name"": ""Walt Disney Pictures""}]",...,8/6/04,113.0,"[{""name"": ""English""}]",Released,It can take a lifetime to find true love.,The Princess Diaries 2: Royal Engagement,princess|royalty,"[{""name"": ""Anne Hathaway""}]",95149435,55149435
2,Whiplash,3300000,"[{""name"": ""Drama""}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,A young drummer faces a ruthless instructor.,64.299990,"[{""name"": ""Bold Films""}]",...,10/10/14,105.0,"[{""name"": ""English""}]",Released,The road to greatness can take you to the edge.,Whiplash,jazz|music,"[{""name"": ""Miles Teller""}]",13092000,9792000
3,Kahaani,1200000,"[{""name"": ""Thriller""}, {""name"": ""Drama""}]",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,A woman searches for her missing husband in Ko...,3.174936,NaN,...,3/9/12,122.0,"[{""name"": ""English|Hindi""}]",Released,NaN,Kahaani,mystery|kolkata,"[{""name"": ""Vidya Balan""}]",16000000,14800000
4,Marine Boy,0,"[{""name"": ""Action""}, {""name"": ""Thriller""}]",NaN,tt1380152,ko,Marine Boy,A former swimmer becomes involved in crime.,1.148070,NaN,...,2/5/09,118.0,"[{""name"": ""Korean""}]",Released,NaN,Marine Boy,NaN,"[{""name"": ""Kim Kang-woo""}]",3923970,3923970

## **We can do a lot of basic operations as well**

In [38]:
# Find the sum of values in a column
df['budget'].sum()

np.int64(3028900000)

In [39]:
# What if there is a null value
df.loc[:1,'revenue'] = np.nan

In [40]:
df.iloc[:5]

,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,production_companies,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,revenue,movie_profit
0,Hot Tub Time Machine 2,14000000,"[{""name"": ""Comedy""}]",NaN,tt2637294,en,Hot Tub Time Machine 2,Time travel comedy.,6.575393,"[{""name"": ""Paramount Pictures""}]",...,2/20/15,93.0,"[{""name"": ""English""}]",Released,The Laws of Space and Time,Hot Tub Time Machine 2,time travel,"[{""name"": ""Rob Corddry""}]",NaN,-1685349
1,The Princess Diaries 2: Royal Engagement,40000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,A princess prepares for marriage.,8.248895,"[{""name"": ""Walt Disney Pictures""}]",...,8/6/04,113.0,"[{""name"": ""English""}]",Released,It can take a lifetime to find true love.,The Princess Diaries 2: Royal Engagement,princess|royalty,"[{""name"": ""Anne Hathaway""}]",NaN,55149435
2,Whiplash,3300000,"[{""name"": ""Drama""}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,A young drummer faces a ruthless instructor.,64.299990,"[{""name"": ""Bold Films""}]",...,10/10/14,105.0,"[{""name"": ""English""}]",Released,The road to greatness can take you to the edge.,Whiplash,jazz|music,"[{""name"": ""Miles Teller""}]",13092000.0,9792000
3,Kahaani,1200000,"[{""name"": ""Thriller""}, {""name"": ""Drama""}]",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,A woman searches for her missing husband in Ko...,3.174936,NaN,...,3/9/12,122.0,"[{""name"": ""English|Hindi""}]",Released,NaN,Kahaani,mystery|kolkata,"[{""name"": ""Vidya Balan""}]",16000000.0,14800000
4,Marine Boy,0,"[{""name"": ""Action""}, {""name"": ""Thriller""}]",NaN,tt1380152,ko,Marine Boy,A former swimmer becomes involved in crime.,1.148070,NaN,...,2/5/09,118.0,"[{""name"": ""Korean""}]",Released,NaN,Marine Boy,NaN,"[{""name"": ""Kim Kang-woo""}]",3923970.0,3923970

In [41]:
df.set_index('imdb_id', inplace=True)

In [42]:
df.head()

,belongs_to_collection,budget,genres,homepage,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,revenue,movie_profit
imdb_id,,,,,,,,,,,,,,,,,,,,
tt2637294,Hot Tub Time Machine 2,14000000,"[{""name"": ""Comedy""}]",NaN,en,Hot Tub Time Machine 2,Time travel comedy.,6.575393,"[{""name"": ""Paramount Pictures""}]","[{""iso_3166_1"": ""US""}]",2/20/15,93.0,"[{""name"": ""English""}]",Released,The Laws of Space and Time,Hot Tub Time Machine 2,time travel,"[{""name"": ""Rob Corddry""}]",NaN,-1685349
tt0368933,The Princess Diaries 2: Royal Engagement,40000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",NaN,en,The Princess Diaries 2: Royal Engagement,A princess prepares for marriage.,8.248895,"[{""name"": ""Walt Disney Pictures""}]","[{""iso_3166_1"": ""US""}]",8/6/04,113.0,"[{""name"": ""English""}]",Released,It can take a lifetime to find true love.,The Princess Diaries 2: Royal Engagement,princess|royalty,"[{""name"": ""Anne Hathaway""}]",NaN,55149435
tt2582802,Whiplash,3300000,"[{""name"": ""Drama""}]",http://sonyclassics.com/whiplash/,en,Whiplash,A young drummer faces a ruthless instructor.,64.299990,"[{""name"": ""Bold Films""}]","[{""iso_3166_1"": ""US""}]",10/10/14,105.0,"[{""name"": ""English""}]",Released,The road to greatness can take you to the edge.,Whiplash,jazz|music,"[{""name"": ""Miles Teller""}]",13092000.0,9792000
tt1821480,Kahaani,1200000,"[{""name"": ""Thriller""}, {""name"": ""Drama""}]",http://kahaanithefilm.com/,hi,Kahaani,A woman searches for her missing husband in Ko...,3.174936,NaN,"[{""iso_3166_1"": ""IN""}]",3/9/12,122.0,"[{""name"": ""English|Hindi""}]",Released,NaN,Kahaani,mystery|kolkata,"[{""name"": ""Vidya Balan""}]",16000000.0,14800000
tt1380152,Marine Boy,0,"[{""name"": ""Action""}, {""name"": ""Thriller""}]",NaN,ko,Marine Boy,A former swimmer becomes involved in crime.,1.148070,NaN,"[{""iso_3166_1"": ""KR""}]",2/5/09,118.0,"[{""name"": ""Korean""}]",Released,NaN,Marine Boy,NaN,"[{""name"": ""Kim Kang-woo""}]",3923970.0,3923970

In [43]:
df.iloc[:3]

,belongs_to_collection,budget,genres,homepage,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,revenue,movie_profit
imdb_id,,,,,,,,,,,,,,,,,,,,
tt2637294,Hot Tub Time Machine 2,14000000,"[{""name"": ""Comedy""}]",NaN,en,Hot Tub Time Machine 2,Time travel comedy.,6.575393,"[{""name"": ""Paramount Pictures""}]","[{""iso_3166_1"": ""US""}]",2/20/15,93.0,"[{""name"": ""English""}]",Released,The Laws of Space and Time,Hot Tub Time Machine 2,time travel,"[{""name"": ""Rob Corddry""}]",NaN,-1685349
tt0368933,The Princess Diaries 2: Royal Engagement,40000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",NaN,en,The Princess Diaries 2: Royal Engagement,A princess prepares for marriage.,8.248895,"[{""name"": ""Walt Disney Pictures""}]","[{""iso_3166_1"": ""US""}]",8/6/04,113.0,"[{""name"": ""English""}]",Released,It can take a lifetime to find true love.,The Princess Diaries 2: Royal Engagement,princess|royalty,"[{""name"": ""Anne Hathaway""}]",NaN,55149435
tt2582802,Whiplash,3300000,"[{""name"": ""Drama""}]",http://sonyclassics.com/whiplash/,en,Whiplash,A young drummer faces a ruthless instructor.,64.299990,"[{""name"": ""Bold Films""}]","[{""iso_3166_1"": ""US""}]",10/10/14,105.0,"[{""name"": ""English""}]",Released,The road to greatness can take you to the edge.,Whiplash,jazz|music,"[{""name"": ""Miles Teller""}]",13092000.0,9792000

In [44]:
df.loc[['tt2637294','tt0368933']]

,belongs_to_collection,budget,genres,homepage,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,revenue,movie_profit
imdb_id,,,,,,,,,,,,,,,,,,,,
tt2637294,Hot Tub Time Machine 2,14000000,"[{""name"": ""Comedy""}]",NaN,en,Hot Tub Time Machine 2,Time travel comedy.,6.575393,"[{""name"": ""Paramount Pictures""}]","[{""iso_3166_1"": ""US""}]",2/20/15,93.0,"[{""name"": ""English""}]",Released,The Laws of Space and Time,Hot Tub Time Machine 2,time travel,"[{""name"": ""Rob Corddry""}]",NaN,-1685349
tt0368933,The Princess Diaries 2: Royal Engagement,40000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",NaN,en,The Princess Diaries 2: Royal Engagement,A princess prepares for marriage.,8.248895,"[{""name"": ""Walt Disney Pictures""}]","[{""iso_3166_1"": ""US""}]",8/6/04,113.0,"[{""name"": ""English""}]",Released,It can take a lifetime to find true love.,The Princess Diaries 2: Royal Engagement,princess|royalty,"[{""name"": ""Anne Hathaway""}]",NaN,55149435

In [45]:
df.head()

,belongs_to_collection,budget,genres,homepage,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,revenue,movie_profit
imdb_id,,,,,,,,,,,,,,,,,,,,
tt2637294,Hot Tub Time Machine 2,14000000,"[{""name"": ""Comedy""}]",NaN,en,Hot Tub Time Machine 2,Time travel comedy.,6.575393,"[{""name"": ""Paramount Pictures""}]","[{""iso_3166_1"": ""US""}]",2/20/15,93.0,"[{""name"": ""English""}]",Released,The Laws of Space and Time,Hot Tub Time Machine 2,time travel,"[{""name"": ""Rob Corddry""}]",NaN,-1685349
tt0368933,The Princess Diaries 2: Royal Engagement,40000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",NaN,en,The Princess Diaries 2: Royal Engagement,A princess prepares for marriage.,8.248895,"[{""name"": ""Walt Disney Pictures""}]","[{""iso_3166_1"": ""US""}]",8/6/04,113.0,"[{""name"": ""English""}]",Released,It can take a lifetime to find true love.,The Princess Diaries 2: Royal Engagement,princess|royalty,"[{""name"": ""Anne Hathaway""}]",NaN,55149435
tt2582802,Whiplash,3300000,"[{""name"": ""Drama""}]",http://sonyclassics.com/whiplash/,en,Whiplash,A young drummer faces a ruthless instructor.,64.299990,"[{""name"": ""Bold Films""}]","[{""iso_3166_1"": ""US""}]",10/10/14,105.0,"[{""name"": ""English""}]",Released,The road to greatness can take you to the edge.,Whiplash,jazz|music,"[{""name"": ""Miles Teller""}]",13092000.0,9792000
tt1821480,Kahaani,1200000,"[{""name"": ""Thriller""}, {""name"": ""Drama""}]",http://kahaanithefilm.com/,hi,Kahaani,A woman searches for her missing husband in Ko...,3.174936,NaN,"[{""iso_3166_1"": ""IN""}]",3/9/12,122.0,"[{""name"": ""English|Hindi""}]",Released,NaN,Kahaani,mystery|kolkata,"[{""name"": ""Vidya Balan""}]",16000000.0,14800000
tt1380152,Marine Boy,0,"[{""name"": ""Action""}, {""name"": ""Thriller""}]",NaN,ko,Marine Boy,A former swimmer becomes involved in crime.,1.148070,NaN,"[{""iso_3166_1"": ""KR""}]",2/5/09,118.0,"[{""name"": ""Korean""}]",Released,NaN,Marine Boy,NaN,"[{""name"": ""Kim Kang-woo""}]",3923970.0,3923970

In [46]:
df['runtime'].sum()

np.float64(3846.0)

In [47]:
print(f" The shortest movie length is {df['runtime'].min()}")
print(f" The largest movie length is {df['runtime'].max()}")

 The shortest movie length is 0.0
 The largest movie length is 194.0

In [48]:
df[df['runtime']== 0.0]

,belongs_to_collection,budget,genres,homepage,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,revenue,movie_profit
imdb_id,,,,,,,,,,,,,,,,,,,,
tt9000001,3 Idiots Returns,80000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",NaN,hi,3 Idiots Returns,Friends reunite years after college.,18.2,"[{""name"": ""Demo Studios""}]","[{""iso_3166_1"": ""IN""}]",8/15/20,0.0,"[{""name"": ""Hindi""}]",Rumored,NaN,3 Idiots Returns,college,"[{""name"": ""Aamir Khan""}]",0.0,-80000000

# **<code>apply()</code>** method applies a function to every row in a pandas dataframe

In [49]:
# Suppose we want to convert the column network to uppercase

def to_uppercase(column):
  return column.upper()

In [50]:
df['Capitalized_title'] = df['title'].apply(to_uppercase)

In [51]:
df.head()

,belongs_to_collection,budget,genres,homepage,original_language,original_title,overview,popularity,production_companies,production_countries,...,runtime,spoken_languages,status,tagline,title,Keywords,cast,revenue,movie_profit,Capitalized_title
imdb_id,,,,,,,,,,,,,,,,,,,,,
tt2637294,Hot Tub Time Machine 2,14000000,"[{""name"": ""Comedy""}]",NaN,en,Hot Tub Time Machine 2,Time travel comedy.,6.575393,"[{""name"": ""Paramount Pictures""}]","[{""iso_3166_1"": ""US""}]",...,93.0,"[{""name"": ""English""}]",Released,The Laws of Space and Time,Hot Tub Time Machine 2,time travel,"[{""name"": ""Rob Corddry""}]",NaN,-1685349,HOT TUB TIME MACHINE 2
tt0368933,The Princess Diaries 2: Royal Engagement,40000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",NaN,en,The Princess Diaries 2: Royal Engagement,A princess prepares for marriage.,8.248895,"[{""name"": ""Walt Disney Pictures""}]","[{""iso_3166_1"": ""US""}]",...,113.0,"[{""name"": ""English""}]",Released,It can take a lifetime to find true love.,The Princess Diaries 2: Royal Engagement,princess|royalty,"[{""name"": ""Anne Hathaway""}]",NaN,55149435,THE PRINCESS DIARIES 2: ROYAL ENGAGEMENT
tt2582802,Whiplash,3300000,"[{""name"": ""Drama""}]",http://sonyclassics.com/whiplash/,en,Whiplash,A young drummer faces a ruthless instructor.,64.299990,"[{""name"": ""Bold Films""}]","[{""iso_3166_1"": ""US""}]",...,105.0,"[{""name"": ""English""}]",Released,The road to greatness can take you to the edge.,Whiplash,jazz|music,"[{""name"": ""Miles Teller""}]",13092000.0,9792000,WHIPLASH
tt1821480,Kahaani,1200000,"[{""name"": ""Thriller""}, {""name"": ""Drama""}]",http://kahaanithefilm.com/,hi,Kahaani,A woman searches for her missing husband in Ko...,3.174936,NaN,"[{""iso_3166_1"": ""IN""}]",...,122.0,"[{""name"": ""English|Hindi""}]",Released,NaN,Kahaani,mystery|kolkata,"[{""name"": ""Vidya Balan""}]",16000000.0,14800000,KAHAANI
tt1380152,Marine Boy,0,"[{""name"": ""Action""}, {""name"": ""Thriller""}]",NaN,ko,Marine Boy,A former swimmer becomes involved in crime.,1.148070,NaN,"[{""iso_3166_1"": ""KR""}]",...,118.0,"[{""name"": ""Korean""}]",Released,NaN,Marine Boy,NaN,"[{""name"": ""Kim Kang-woo""}]",3923970.0,3923970,MARINE BOY

## Another way to use <code>apply()</code> involves the use of <code>lambda()</code> function.

* ### A <code>lambda()</code> function is a small anonymous function.
* ### A <code>lambda()</code> function can take any number of arguments, but can only have one expression.

In [52]:
def add_two_numbers(a,b):
  return a+b

In [53]:
x = lambda a,b : a+b
x(1,5)

6

In [54]:
# lambda function - Row wise operation
def revised_profit(revenue, budget):
  if revenue > 0:
    new_profit = revenue - budget
  else:
    new_profit = np.nan

  return new_profit

In [55]:
df['new_profit'] = df.apply(lambda x: revised_profit(x['revenue'], x['budget']),axis=1)

In [56]:
df.head()

,belongs_to_collection,budget,genres,homepage,original_language,original_title,overview,popularity,production_companies,production_countries,...,spoken_languages,status,tagline,title,Keywords,cast,revenue,movie_profit,Capitalized_title,new_profit
imdb_id,,,,,,,,,,,,,,,,,,,,,
tt2637294,Hot Tub Time Machine 2,14000000,"[{""name"": ""Comedy""}]",NaN,en,Hot Tub Time Machine 2,Time travel comedy.,6.575393,"[{""name"": ""Paramount Pictures""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,The Laws of Space and Time,Hot Tub Time Machine 2,time travel,"[{""name"": ""Rob Corddry""}]",NaN,-1685349,HOT TUB TIME MACHINE 2,NaN
tt0368933,The Princess Diaries 2: Royal Engagement,40000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",NaN,en,The Princess Diaries 2: Royal Engagement,A princess prepares for marriage.,8.248895,"[{""name"": ""Walt Disney Pictures""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,It can take a lifetime to find true love.,The Princess Diaries 2: Royal Engagement,princess|royalty,"[{""name"": ""Anne Hathaway""}]",NaN,55149435,THE PRINCESS DIARIES 2: ROYAL ENGAGEMENT,NaN
tt2582802,Whiplash,3300000,"[{""name"": ""Drama""}]",http://sonyclassics.com/whiplash/,en,Whiplash,A young drummer faces a ruthless instructor.,64.299990,"[{""name"": ""Bold Films""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,The road to greatness can take you to the edge.,Whiplash,jazz|music,"[{""name"": ""Miles Teller""}]",13092000.0,9792000,WHIPLASH,9792000.0
tt1821480,Kahaani,1200000,"[{""name"": ""Thriller""}, {""name"": ""Drama""}]",http://kahaanithefilm.com/,hi,Kahaani,A woman searches for her missing husband in Ko...,3.174936,NaN,"[{""iso_3166_1"": ""IN""}]",...,"[{""name"": ""English|Hindi""}]",Released,NaN,Kahaani,mystery|kolkata,"[{""name"": ""Vidya Balan""}]",16000000.0,14800000,KAHAANI,14800000.0
tt1380152,Marine Boy,0,"[{""name"": ""Action""}, {""name"": ""Thriller""}]",NaN,ko,Marine Boy,A former swimmer becomes involved in crime.,1.148070,NaN,"[{""iso_3166_1"": ""KR""}]",...,"[{""name"": ""Korean""}]",Released,NaN,Marine Boy,NaN,"[{""name"": ""Kim Kang-woo""}]",3923970.0,3923970,MARINE BOY,3923970.0

## We can also sort our dataframe by some column values in either an ascending or descending order

In [57]:
# Sort values in descending order
df.sort_values('runtime', ascending=False)

,belongs_to_collection,budget,genres,homepage,original_language,original_title,overview,popularity,production_companies,production_countries,...,spoken_languages,status,tagline,title,Keywords,cast,revenue,movie_profit,Capitalized_title,new_profit
imdb_id,,,,,,,,,,,,,,,,,,,,,
tt0120338,Titanic,200000000,"[{""name"": ""Drama""}, {""name"": ""Romance""}]",NaN,en,Titanic,A romance unfolds aboard a doomed ship.,78.500000,"[{""name"": ""20th Century Fox""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,Nothing on Earth could come between them.,Titanic,ship|romance,"[{""name"": ""Leonardo DiCaprio""}]",2.264743e+09,2064743305,TITANIC,2.064743e+09
tt8178634,RRR,550000000,"[{""name"": ""Action""}, {""name"": ""Drama""}]",NaN,te,RRR,Two revolutionaries form an unlikely friendship.,60.300000,"[{""name"": ""DVV Entertainment""}]","[{""iso_3166_1"": ""IN""}]",...,"[{""name"": ""Telugu""}]",Released,Rise. Roar. Revolt.,RRR,friendship|revolution,"[{""name"": ""N. T. Rama Rao Jr.""}]",1.200000e+09,650000000,RRR,6.500000e+08
tt0112870,Dilwale Dulhania Le Jayenge,40000000,"[{""name"": ""Drama""}, {""name"": ""Romance""}]",NaN,hi,Dilwale Dulhania Le Jayenge,A young couple challenges family expectations.,20.600000,"[{""name"": ""Yash Raj Films""}]","[{""iso_3166_1"": ""IN""}]",...,"[{""name"": ""Hindi""}]",Released,Come... Fall in love.,Dilwale Dulhania Le Jayenge,romance|family,"[{""name"": ""Shah Rukh Khan""}]",1.200000e+08,80000000,DILWALE DULHANIA LE JAYENGE,8.000000e+07
tt4154796,Avengers: Endgame,356000000,"[{""name"": ""Action""}, {""name"": ""Adventure""}, {""...",NaN,en,Avengers: Endgame,Heroes attempt to reverse a devastating loss.,88.200000,"[{""name"": ""Marvel Studios""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,Avenge the fallen.,Avengers: Endgame,superhero|marvel,"[{""name"": ""Robert Downey Jr.""}]",2.797501e+09,2441501328,AVENGERS: ENDGAME,2.441501e+09
tt0068646,The Godfather,6000000,"[{""name"": ""Crime""}, {""name"": ""Drama""}]",NaN,en,The Godfather,The aging patriarch transfers control of his e...,95.300000,"[{""name"": ""Paramount Pictures""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,An offer you can't refuse.,The Godfather,mafia|family,"[{""name"": ""Marlon Brando""}]",2.500000e+08,244000000,THE GODFATHER,2.440000e+08
tt1187043,3 Idiots,550000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",https://example.com/3idiots,hi,3 Idiots,Three friends navigate college and life.,25.300000,"[{""name"": ""Vinod Chopra Films""}]","[{""iso_3166_1"": ""IN""}]",...,"[{""name"": ""Hindi""}]",Released,All is well.,3 Idiots,college|friendship,"[{""name"": ""Aamir Khan""}]",2.000000e+09,1450000000,3 IDIOTS,1.450000e+09
tt0816692,Interstellar,165000000,"[{""name"": ""Adventure""}, {""name"": ""Drama""}, {""n...",NaN,en,Interstellar,Explorers travel through a wormhole in space.,75.000000,"[{""name"": ""Paramount Pictures""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,Mankind was born on Earth. It was never meant ...,Interstellar,space|wormhole,"[{""name"": ""Matthew McConaughey""}]",7.017292e+08,536729206,INTERSTELLAR,5.367292e+08
tt4849438,Bahubali 2: The Conclusion,250000000,"[{""name"": ""Action""}, {""name"": ""Drama""}]",NaN,te,Baahubali 2: The Conclusion,A kingdom seeks answers and revenge.,52.900000,"[{""name"": ""Arka Media Works""}]","[{""iso_3166_1"": ""IN""}]",...,"[{""name"": ""Telugu""}]",Released,Why did Kattappa kill Baahubali?,Baahubali 2: The Conclusion,kingdom|war,"[{""name"": ""Prabhas""}]",1.810000e+09,1560000000,BAAHUBALI 2: THE CONCLUSION,1.560000e+09
tt5074352,Dangal,70000000,"[{""name"": ""Drama""}, {""name"": ""Sport""}]",NaN,hi,Dangal,A father trains his daughters to become wrestl...,35.400000,"[{""name"": ""Aamir Khan Productions""}]","[{""iso_3166_1"": ""IN""}]",...,"[{""name"": ""Hindi""}]",Released,Gold is pure. So is Dangal.,Dangal,wrestling|family,"[{""name"": ""Aamir Khan""}]",3.100000e+08,240000000,DANGAL,2.400000e+08
tt0468569,The Dark Knight,185000000,"[{""name"": ""Action""}, {""name"": ""Crime""}, {""name...",NaN,en,The Dark Knight,Batman faces the Joker.,90.100000,"[{""name"": ""Warner Bros.""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,Why so serious?,The Dark Knight,joker|batman,"[{""name"": ""Christian Bale""}]",1.004558e+09,819558444,THE DARK KNIGHT,8.195584e+08
tt1375666,Inception,160000000,"[{""name"": ""Action""}, {""name"": ""Sci-Fi""}]",https://example.com/inception,en,Inception,A thief enters dreams to steal secrets.,82.500000,"[{""name"": ""Warner Bros.""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,Your mind is the scene of the crime.,Inception,dream|heist,"[{""name"": ""Leonardo DiCaprio""}]",8.390000e+08,679000000,INCEPTION,6.790000e+08
tt15327088,Kantara,16000000,"[{""name"": ""Action""}, {""name"": ""Drama""}]",https://example.com/kantara,kn,Kantara,A village conflict involving tradition and nat...,42.700000,"[{""name"": ""Hombale Films""}]","[{""iso_3166_1"": ""IN""}]",...,"[{""name"": ""Kannada""}]",Released,"When tradition calls, destiny answers.",Kantara,village|tradition,"[{""name"": ""Rishab Shetty""}]",4.000000e+08,384000000,KANTARA,3.840000e+08
tt6751668,Parasite,11400000,"[{""name"": ""Drama""}, {""name"": ""Thriller""}]",NaN,ko,Parasite,Two families become entangled in a strange sit...,55.700000,"[{""name"": ""Barunson E&A""}]","[{""iso_3166_1"": ""KR""}]",...,"[{""name"": ""Korean""}]",Released,Act like you own the place.,Parasite,family|class,"[{""name"": ""Song Kang-ho""}]",2.580000e+08,246600000,PARASITE,2.466000e+08
tt0362227,The Terminal,60000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",http://www.theterminal-themovie.com/,en,The Terminal,A man becomes stranded in an airport.,14.092373,"[{""name"": ""DreamWorks SKG""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,Life is waiting.,The Terminal,airport|new york,"[{""name"": ""Tom Hanks""}]",2.194173e+08,159417255,THE TERMINAL,1.594173e+08
tt3783958,La La Land,30000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}, {""name...",NaN,en,La La Land,A musician and actress pursue dreams in Los An...,35.800000,"[{""name"": ""Lionsgate""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,Here's to the fools who dream.,La La Land,music|los angeles,"[{""name"": ""Ryan Gosling""}]",4.720000e+08,442000000,LA LA LAND,4.420000e+08
tt0245429,Spirited Away,19000000,"[{""name"": ""Animation""}, {""name"": ""Fantasy""}]",https://example.com/spirited,ja,Spirited Away,A girl enters a mysterious spirit world.,72.100000,"[{""name"": ""Studio Ghibli""}]","[{""iso_3166_1"": ""JP""}]",...,"[{""name"": ""Japanese""}]",Released,The tunnel led Chihiro to a mysterious town.,Spirited Away,spirit|magic,"[{""name"": ""Rumi Hiiragi""}]",3.958000e+08,376800000,SPIRITED AWAY,3.768000e+08
tt7286456,Joker,55000000,"[{""name"": ""Crime""}, {""name"": ""Drama""}]",NaN,en,Joker,A failed comedian descends into chaos.,70.900000,"[{""name"": ""Warner Bros.""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,Put on a happy face.,Joker,joker|crime,"[{""name"": ""Joaquin Phoenix""}]",1.074251e+09,1019251311,JOKER,1.019251e+09
tt1821480,Kahaani,1200000,"[{""name"": ""Thriller""}, {""name"": ""Drama""}]",http://kahaanithefilm.com/,hi,Kahaani,A woman searches for her missing husband in Ko...,3.174936,NaN,"[{""iso_3166_1"": ""IN""}]",...,"[{""name"": ""English|Hindi""}]",Released,NaN,Kahaani,mystery|kolkata,"[{""name"": ""Vidya Balan""}]",1.600000e+07,14800000,KAHAANI,1.480000e+07
tt0116908,The Long Kiss Goodnight,65000000,"[{""name"": ""Crime""}, {""name"": ""Action""}]",NaN,en,The Long Kiss Goodnight,A woman discovers her forgotten past.,14.482345,"[{""name"": ""New Line Cinema""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,assassination|memory,"[{""name"": ""Geena Davis""}]",8.945676e+07,24456761,THE LONG KISS GOODNIGHT,2.445676e+07
tt1380152,Marine Boy,0,"[{""name"": ""Action""}, {""name"": ""Thriller""}]",NaN,ko,Marine Boy,A former swimmer becomes involved in crime.,1.148070,NaN,"[{""iso_3166_1"": ""KR""}]",...,"[{""name"": ""Korean""}]",Released,NaN,Marine Boy,NaN,"[{""name"": ""Kim Kang-woo""}]",3.923970e+06,3923970,MARINE BOY,3.923970e+06
tt0368933,The Princess Diaries 2: Royal Engagement,40000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",NaN,en,The Princess Diaries 2: Royal Engagement,A princess prepares for marriage.,8.248895,"[{""name"": ""Walt Disney Pictures""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,It can take a lifetime to find true love.,The Princess Diaries 2: Royal Engagement,princess|royalty,"[{""name"": ""Anne Hathaway""}]",NaN,55149435,THE PRINCESS DIARIES 2: ROYAL ENGAGEMENT,NaN
tt0105327,School Ties,0,"[{""name"": ""Drama""}]",NaN,en,School Ties,A student faces prejudice at an elite school.,7.438381,"[{""name"": ""Paramount Pictures""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,Just because you’re accepted doesn’t mean you ...,School Ties,school|sport,"[{""name"": ""Brendan Fraser""}]",1.471507e+07,14715067,SCHOOL TIES,1.471507e+07
tt1600195,Abduction,35000000,"[{""name"": ""Thriller""}, {""name"": ""Action""}]",http://www.abductionthefilm.com/,en,Abduction,A young man searches for the truth about his i...,10.512109,"[{""name"": ""Lions Gate Films""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,They stole his life. He's taking it back.,Abduction,CIA|conspiracy,"[{""name"": ""Taylor Lautner""}]",8.208716e+07,47087155,ABDUCTION,4.708716e+07
tt2582802,Whiplash,3300000,"[{""name"": ""Drama""}]",http://sonyclassics.com/whiplash/,en,Whiplash,A young drummer faces a ruthless instructor.,64.299990,"[{""name"": ""Bold Films""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,The road to greatness can take you to the edge.,Whiplash,jazz|music,"[{""name"": ""Miles Teller""}]",1.309200e+07,9792000,WHIPLASH,9.792000e+06
tt0109403,Chasers,0,"[{""name"": ""Comedy""}, {""name"": ""Romance""}]",NaN,en,Chasers,Two military men escort a prisoner.,9.853270,"[{""name"": ""Warner Bros.""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,It was supposed to be a routine prisoner trans...,Chasers,prison|military,"[{""name"": ""Tom Berenger""}]",1.596687e+06,1596687,CHASERS,1.596687e+06
tt2364975,We Are the Best!,0,"[{""name"": ""Drama""}, {""name"": ""Music""}]",NaN,sv,We Are the Best!,Three girls form a punk band.,3.727996,"[{""name"": ""Memfis Film""}]","[{""iso_3166_1"": ""SE""}]",...,"[{""name"": ""Swedish""}]",Released,NaN,We Are the Best!,sweden|punk,"[{""name"": ""Mira Barkhammar""}]",1.805900e+05,180590,WE ARE THE BEST!,1.805900e+05
tt2637294,Hot Tub Time Machine 2,14000000,"[{""name"": ""Comedy""}]",NaN,en,Hot Tub Time Machine 2,Time travel comedy.,6.575393,"[{""name"": ""Paramount Pictures""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,The Laws of Space and Time,Hot Tub Time Machine 2,time travel,"[{""name"": ""Rob Corddry""}]",NaN,-1685349,HOT TUB TIME MACHINE 2,NaN
tt0343135,Along Came Polly,42000000,"[{""name"": ""Comedy""}, {""name"": ""Romance""}]",http://www.alongcamepolly.com/,en,Along Came Polly,A cautious man finds unexpected love.,15.725542,"[{""name"": ""Jersey Films""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,beach|love,"[{""name"": ""Ben Stiller""}]",1.719634e+08,129963386,ALONG CAME POLLY,1.299634e+08
tt9000001,3 Idiots Returns,80000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",NaN,hi,3 Idiots Returns,Friends reunite years after college.,18.200000,"[{""name"": ""Demo Studios""}]","[{""iso_3166_1"": ""IN""}]",...,"[{""name"": ""Hindi""}]",Rumored,NaN,3 Idiots Returns,college,"[{""name"": ""Aamir Khan""}]",0.000000e+00,-80000000,3 IDIOTS RETURNS,NaN
tt9000002,Mystery Movie,25000000,NaN,NaN,en,Mystery Movie,A mystery with incomplete metadata.,12.500000,NaN,"[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,NaN,Mystery Movie,mystery,"[{""name"": ""Unknown""}]",4.500000e+07,20000000,MYSTERY MOVIE,2.000000e+07

In [58]:
# We can also sort by the combination of two columns
df.sort_values(['status','new_profit'], ascending=[False,True]).head()

,belongs_to_collection,budget,genres,homepage,original_language,original_title,overview,popularity,production_companies,production_countries,...,spoken_languages,status,tagline,title,Keywords,cast,revenue,movie_profit,Capitalized_title,new_profit
imdb_id,,,,,,,,,,,,,,,,,,,,,
tt9000001,3 Idiots Returns,80000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",NaN,hi,3 Idiots Returns,Friends reunite years after college.,18.200000,"[{""name"": ""Demo Studios""}]","[{""iso_3166_1"": ""IN""}]",...,"[{""name"": ""Hindi""}]",Rumored,NaN,3 Idiots Returns,college,"[{""name"": ""Aamir Khan""}]",0.0,-80000000,3 IDIOTS RETURNS,NaN
tt2364975,We Are the Best!,0,"[{""name"": ""Drama""}, {""name"": ""Music""}]",NaN,sv,We Are the Best!,Three girls form a punk band.,3.727996,"[{""name"": ""Memfis Film""}]","[{""iso_3166_1"": ""SE""}]",...,"[{""name"": ""Swedish""}]",Released,NaN,We Are the Best!,sweden|punk,"[{""name"": ""Mira Barkhammar""}]",180590.0,180590,WE ARE THE BEST!,180590.0
tt0109403,Chasers,0,"[{""name"": ""Comedy""}, {""name"": ""Romance""}]",NaN,en,Chasers,Two military men escort a prisoner.,9.853270,"[{""name"": ""Warner Bros.""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,It was supposed to be a routine prisoner trans...,Chasers,prison|military,"[{""name"": ""Tom Berenger""}]",1596687.0,1596687,CHASERS,1596687.0
tt1380152,Marine Boy,0,"[{""name"": ""Action""}, {""name"": ""Thriller""}]",NaN,ko,Marine Boy,A former swimmer becomes involved in crime.,1.148070,NaN,"[{""iso_3166_1"": ""KR""}]",...,"[{""name"": ""Korean""}]",Released,NaN,Marine Boy,NaN,"[{""name"": ""Kim Kang-woo""}]",3923970.0,3923970,MARINE BOY,3923970.0
tt2582802,Whiplash,3300000,"[{""name"": ""Drama""}]",http://sonyclassics.com/whiplash/,en,Whiplash,A young drummer faces a ruthless instructor.,64.299990,"[{""name"": ""Bold Films""}]","[{""iso_3166_1"": ""US""}]",...,"[{""name"": ""English""}]",Released,The road to greatness can take you to the edge.,Whiplash,jazz|music,"[{""name"": ""Miles Teller""}]",13092000.0,9792000,WHIPLASH,9792000.0

# <b>Let us explore some datetime operations and functions

Directive

* #### <b>%a</b>	Weekday as locale’s abbreviated name.	Sun, Mon, …, Sat (en_US)
So, Mo, …, Sa (de_DE)
* #### <b>%A</b>	Weekday as locale’s full name.	Sunday, Monday, …, Saturday (en_US)
Sonntag, Montag, …, Samstag (de_DE)
* #### <b>%w</b>	Weekday as a decimal number, where 0 is Sunday and 6 is Saturday.	0, 1, 2, 3, 4, 5, 6
* #### <b>%d</b>	Day of the month as a zero-padded decimal number.	01, 02, …, 31
* #### <b>%b</b>	Month as locale’s abbreviated name.	Jan, Feb, …, Dec (en_US)
Jan, Feb, …, Dez (de_DE)
* #### <b>%B</b>	Month as locale’s full name.	January, February, …, December (en_US)
Januar, Februar, …, Dezember (de_DE)
* #### <b>%m</b>	Month as a zero-padded decimal number.	01, 02 … 12
* #### <b>%y</b>	Year without century as a zero-padded decimal number.	01, 02, … 99
* #### <b>%Y</b>	Year with century as a decimal number.	0001, 0002, … , 9999
* #### <b>%H</b>	Hour (24-hour clock) as a zero-padded decimal number.	01, 02, … , 23
* #### <b>%I</b>	Hour (12-hour clock) as a zero-padded decimal number.	01, 02, … , 12
* #### <b>%p</b>	Locale’s equivalent of either AM or PM.	AM, PM (en_US)
am, pm (de_DE)
* #### <b>%M</b>	Minute as a zero-padded decimal number.	01, 02, … , 59
* #### <b>%S</b>	Second as a zero-padded decimal number.	01, 02, … , 59
* #### <b>%f</b>	Microsecond as a decimal number, zero-padded on the left.	000000, 000001, …, 999999

In [59]:
df.info()

<class 'pandas.DataFrame'>
Index: 30 entries, tt2637294 to tt0112870
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  30 non-null     str
 1   budget                 30 non-null     int64
 2   genres                 29 non-null     str
 3   homepage               9 non-null      str
 4   original_language      30 non-null     str
 5   original_title         30 non-null     str
 6   overview               30 non-null     str
 7   popularity             30 non-null     float64
 8   production_companies   27 non-null     str
 9   production_countries   30 non-null     str
 10  release_date           30 non-null     str
 11  runtime                29 non-null     float64
 12  spoken_languages       30 non-null     str
 13  status                 30 non-null     str
 14  tagline                25 non-null     str
 15  title                  30 non-null     str
 16  Keywords               29 non-null     str
 17  cast                   30 non-null     str
 18  revenue                28 non-null     float64
 19  movie_profit           30 non-null     int64
 20  Capitalized_title      30 non-null     str
 21  new_profit             27 non-null     float64
dtypes: float64(4), int64(2), str(16)
memory usage: 6.4+ KB

In [60]:
df['release_date'][0:5]

imdb_id
tt2637294     2/20/15
tt0368933      8/6/04
tt2582802    10/10/14
tt1821480      3/9/12
tt1380152      2/5/09
Name: release_date, dtype: str

In [61]:
# Importing datetime modules
from datetime import datetime
from datetime import date

## <code>strptime</code> means string parser, this will convert a string format to datetime.

## <code>strftime</code> means string formatter, this will format a datetime object to string format.

In [62]:
df['release_date'][0:5]

imdb_id
tt2637294     2/20/15
tt0368933      8/6/04
tt2582802    10/10/14
tt1821480      3/9/12
tt1380152      2/5/09
Name: release_date, dtype: str

In [63]:
df['new_release_date']=df['release_date'].apply(lambda x : datetime.strptime(x,'%m/%d/%y'))

In [64]:
df.info()

<class 'pandas.DataFrame'>
Index: 30 entries, tt2637294 to tt0112870
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  30 non-null     str
 1   budget                 30 non-null     int64
 2   genres                 29 non-null     str
 3   homepage               9 non-null      str
 4   original_language      30 non-null     str
 5   original_title         30 non-null     str
 6   overview               30 non-null     str
 7   popularity             30 non-null     float64
 8   production_companies   27 non-null     str
 9   production_countries   30 non-null     str
 10  release_date           30 non-null     str
 11  runtime                29 non-null     float64
 12  spoken_languages       30 non-null     str
 13  status                 30 non-null     str
 14  tagline                25 non-null     str
 15  title                  30 non-null     str
 16  Keywords               29 non-null     str
 17  cast                   30 non-null     str
 18  revenue                28 non-null     float64
 19  movie_profit           30 non-null     int64
 20  Capitalized_title      30 non-null     str
 21  new_profit             27 non-null     float64
 22  new_release_date       30 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(4), int64(2), str(16)
memory usage: 6.7+ KB

In [65]:
df.head()

,belongs_to_collection,budget,genres,homepage,original_language,original_title,overview,popularity,production_companies,production_countries,...,status,tagline,title,Keywords,cast,revenue,movie_profit,Capitalized_title,new_profit,new_release_date
imdb_id,,,,,,,,,,,,,,,,,,,,,
tt2637294,Hot Tub Time Machine 2,14000000,"[{""name"": ""Comedy""}]",NaN,en,Hot Tub Time Machine 2,Time travel comedy.,6.575393,"[{""name"": ""Paramount Pictures""}]","[{""iso_3166_1"": ""US""}]",...,Released,The Laws of Space and Time,Hot Tub Time Machine 2,time travel,"[{""name"": ""Rob Corddry""}]",NaN,-1685349,HOT TUB TIME MACHINE 2,NaN,2015-02-20
tt0368933,The Princess Diaries 2: Royal Engagement,40000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",NaN,en,The Princess Diaries 2: Royal Engagement,A princess prepares for marriage.,8.248895,"[{""name"": ""Walt Disney Pictures""}]","[{""iso_3166_1"": ""US""}]",...,Released,It can take a lifetime to find true love.,The Princess Diaries 2: Royal Engagement,princess|royalty,"[{""name"": ""Anne Hathaway""}]",NaN,55149435,THE PRINCESS DIARIES 2: ROYAL ENGAGEMENT,NaN,2004-08-06
tt2582802,Whiplash,3300000,"[{""name"": ""Drama""}]",http://sonyclassics.com/whiplash/,en,Whiplash,A young drummer faces a ruthless instructor.,64.299990,"[{""name"": ""Bold Films""}]","[{""iso_3166_1"": ""US""}]",...,Released,The road to greatness can take you to the edge.,Whiplash,jazz|music,"[{""name"": ""Miles Teller""}]",13092000.0,9792000,WHIPLASH,9792000.0,2014-10-10
tt1821480,Kahaani,1200000,"[{""name"": ""Thriller""}, {""name"": ""Drama""}]",http://kahaanithefilm.com/,hi,Kahaani,A woman searches for her missing husband in Ko...,3.174936,NaN,"[{""iso_3166_1"": ""IN""}]",...,Released,NaN,Kahaani,mystery|kolkata,"[{""name"": ""Vidya Balan""}]",16000000.0,14800000,KAHAANI,14800000.0,2012-03-09
tt1380152,Marine Boy,0,"[{""name"": ""Action""}, {""name"": ""Thriller""}]",NaN,ko,Marine Boy,A former swimmer becomes involved in crime.,1.148070,NaN,"[{""iso_3166_1"": ""KR""}]",...,Released,NaN,Marine Boy,NaN,"[{""name"": ""Kim Kang-woo""}]",3923970.0,3923970,MARINE BOY,3923970.0,2009-02-05

In [83]:
df['new_release_date'].iloc[0]

Timestamp('2015-02-20 00:00:00')

In [85]:
# Month year date
print(df['new_release_date'][0].month)
print(df['new_release_date'][0].year)
print(df['new_release_date'][0].day)
print(df['new_release_date'][0].hour)
print(df['new_release_date'][0].minute)

KeyError: 0

In [ ]:
print(date.today())
print(datetime.now())

2021-02-17
2021-02-17 16:19:20.428727

In [ ]:
datetime.now() + 1

TypeError: ignored

In [ ]:
# Some operations we can do on datetime
from datetime import timedelta
print(date.today())
print(date.today() - timedelta(days=1))
print(datetime.now() + timedelta(hours=5.5))
print(datetime.now() + timedelta(seconds=60))

2021-02-17
2021-02-16
2021-02-17 21:52:15.067322
2021-02-17 16:23:15.067618

In [ ]:
print(df['new_release_date'][0])
print(df['new_release_date'][5])

2015-02-20 00:00:00
1987-08-06 00:00:00

In [ ]:
# Difference in two datetime
time_delta=df['new_release_date'][0]-df['new_release_date'][5]
time_delta

Timedelta('10060 days 00:00:00')

In [ ]:
type(time_delta)

pandas._libs.tslibs.timedeltas.Timedelta

In [68]:
t1 = pd.to_datetime('1/1/2015 01:00')
t2 = pd.to_datetime('1/1/2015 03:30')

print(pd.Timedelta(t2 - t1).seconds / 3600.0)

2.5

# **Let's explore the unique and missing values**

* ### <code>unique()</code>
* ### <code>nunique()</code>
* ### <code>value_counts()</code>
* ### <code>isnull()</code>
* ### <code>fillna()</code>

In [69]:
df.info()

<class 'pandas.DataFrame'>
Index: 30 entries, tt2637294 to tt0112870
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  30 non-null     str
 1   budget                 30 non-null     int64
 2   genres                 29 non-null     str
 3   homepage               9 non-null      str
 4   original_language      30 non-null     str
 5   original_title         30 non-null     str
 6   overview               30 non-null     str
 7   popularity             30 non-null     float64
 8   production_companies   27 non-null     str
 9   production_countries   30 non-null     str
 10  release_date           30 non-null     str
 11  runtime                29 non-null     float64
 12  spoken_languages       30 non-null     str
 13  status                 30 non-null     str
 14  tagline                25 non-null     str
 15  title                  30 non-null     str
 16  Keywords               29 non-null     str
 17  cast                   30 non-null     str
 18  revenue                28 non-null     float64
 19  movie_profit           30 non-null     int64
 20  Capitalized_title      30 non-null     str
 21  new_profit             27 non-null     float64
 22  new_release_date       30 non-null     datetime64[us]
dtypes: datetime64[us](1), float64(4), int64(2), str(16)
memory usage: 6.7+ KB

In [70]:
# Find the list of unique values in a column
list(df['status'].unique())

['Released', 'Rumored']

In [71]:
list(df['original_language'].unique())

['en', 'hi', 'ko', 'sv', 'ja', 'kn', 'te']

In [72]:
# Counts the number of unique values in a column
df.original_language.nunique()

7

In [73]:
# Give the counts of each category of a variable
df['original_language'].value_counts()

original_language
en    18
hi     5
ko     2
te     2
sv     1
ja     1
kn     1
Name: count, dtype: int64

In [74]:
# Does not make much sense to use value_counts for a numeric variable
df.runtime.value_counts()

runtime
122.0    2
148.0    2
128.0    2
106.0    2
102.0    2
181.0    2
93.0     1
113.0    1
105.0    1
118.0    1
152.0    1
170.0    1
132.0    1
120.0    1
90.0     1
169.0    1
161.0    1
194.0    1
125.0    1
175.0    1
0.0      1
187.0    1
168.0    1
Name: count, dtype: int64

In [75]:
# Returns a series of booleans if a column value contains nulls
df['homepage'].isnull()

imdb_id
tt2637294      True
tt0368933      True
tt2582802     False
tt1821480     False
tt1380152      True
tt1375666     False
tt0468569      True
tt1187043     False
tt6751668      True
tt0362227     False
tt0105327      True
tt0109403      True
tt2364975      True
tt0116908      True
tt0343135     False
tt1600195     False
tt0816692      True
tt5074352      True
tt4154796      True
tt0120338      True
tt0245429     False
tt0068646      True
tt9000001      True
tt9000002      True
tt15327088    False
tt8178634      True
tt4849438      True
tt7286456      True
tt3783958      True
tt0112870      True
Name: homepage, dtype: bool

In [76]:
df[~df['homepage'].isnull()]

,belongs_to_collection,budget,genres,homepage,original_language,original_title,overview,popularity,production_companies,production_countries,...,status,tagline,title,Keywords,cast,revenue,movie_profit,Capitalized_title,new_profit,new_release_date
imdb_id,,,,,,,,,,,,,,,,,,,,,
tt2582802,Whiplash,3300000,"[{""name"": ""Drama""}]",http://sonyclassics.com/whiplash/,en,Whiplash,A young drummer faces a ruthless instructor.,64.299990,"[{""name"": ""Bold Films""}]","[{""iso_3166_1"": ""US""}]",...,Released,The road to greatness can take you to the edge.,Whiplash,jazz|music,"[{""name"": ""Miles Teller""}]",1.309200e+07,9792000,WHIPLASH,9.792000e+06,2014-10-10
tt1821480,Kahaani,1200000,"[{""name"": ""Thriller""}, {""name"": ""Drama""}]",http://kahaanithefilm.com/,hi,Kahaani,A woman searches for her missing husband in Ko...,3.174936,NaN,"[{""iso_3166_1"": ""IN""}]",...,Released,NaN,Kahaani,mystery|kolkata,"[{""name"": ""Vidya Balan""}]",1.600000e+07,14800000,KAHAANI,1.480000e+07,2012-03-09
tt1375666,Inception,160000000,"[{""name"": ""Action""}, {""name"": ""Sci-Fi""}]",https://example.com/inception,en,Inception,A thief enters dreams to steal secrets.,82.500000,"[{""name"": ""Warner Bros.""}]","[{""iso_3166_1"": ""US""}]",...,Released,Your mind is the scene of the crime.,Inception,dream|heist,"[{""name"": ""Leonardo DiCaprio""}]",8.390000e+08,679000000,INCEPTION,6.790000e+08,2010-07-16
tt1187043,3 Idiots,550000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",https://example.com/3idiots,hi,3 Idiots,Three friends navigate college and life.,25.300000,"[{""name"": ""Vinod Chopra Films""}]","[{""iso_3166_1"": ""IN""}]",...,Released,All is well.,3 Idiots,college|friendship,"[{""name"": ""Aamir Khan""}]",2.000000e+09,1450000000,3 IDIOTS,1.450000e+09,2009-12-25
tt0362227,The Terminal,60000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",http://www.theterminal-themovie.com/,en,The Terminal,A man becomes stranded in an airport.,14.092373,"[{""name"": ""DreamWorks SKG""}]","[{""iso_3166_1"": ""US""}]",...,Released,Life is waiting.,The Terminal,airport|new york,"[{""name"": ""Tom Hanks""}]",2.194173e+08,159417255,THE TERMINAL,1.594173e+08,2004-06-17
tt0343135,Along Came Polly,42000000,"[{""name"": ""Comedy""}, {""name"": ""Romance""}]",http://www.alongcamepolly.com/,en,Along Came Polly,A cautious man finds unexpected love.,15.725542,"[{""name"": ""Jersey Films""}]","[{""iso_3166_1"": ""US""}]",...,Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,beach|love,"[{""name"": ""Ben Stiller""}]",1.719634e+08,129963386,ALONG CAME POLLY,1.299634e+08,2004-01-16
tt1600195,Abduction,35000000,"[{""name"": ""Thriller""}, {""name"": ""Action""}]",http://www.abductionthefilm.com/,en,Abduction,A young man searches for the truth about his i...,10.512109,"[{""name"": ""Lions Gate Films""}]","[{""iso_3166_1"": ""US""}]",...,Released,They stole his life. He's taking it back.,Abduction,CIA|conspiracy,"[{""name"": ""Taylor Lautner""}]",8.208716e+07,47087155,ABDUCTION,4.708716e+07,2011-09-22
tt0245429,Spirited Away,19000000,"[{""name"": ""Animation""}, {""name"": ""Fantasy""}]",https://example.com/spirited,ja,Spirited Away,A girl enters a mysterious spirit world.,72.100000,"[{""name"": ""Studio Ghibli""}]","[{""iso_3166_1"": ""JP""}]",...,Released,The tunnel led Chihiro to a mysterious town.,Spirited Away,spirit|magic,"[{""name"": ""Rumi Hiiragi""}]",3.958000e+08,376800000,SPIRITED AWAY,3.768000e+08,2001-07-20
tt15327088,Kantara,16000000,"[{""name"": ""Action""}, {""name"": ""Drama""}]",https://example.com/kantara,kn,Kantara,A village conflict involving tradition and nat...,42.700000,"[{""name"": ""Hombale Films""}]","[{""iso_3166_1"": ""IN""}]",...,Released,"When tradition calls, destiny answers.",Kantara,village|tradition,"[{""name"": ""Rishab Shetty""}]",4.000000e+08,384000000,KANTARA,3.840000e+08,2022-09-30

In [77]:
# Lets fill the missing values with the value -999
df['homepage'].fillna('Not Present',inplace = True)

C:\Users\LakshmanAIMLHYD\AppData\Local\Temp\ipykernel_8920\1233594187.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['homepage'].fillna('Not Present',inplace = True)

imdb_id
tt2637294                              Not Present
tt0368933                              Not Present
tt2582802        http://sonyclassics.com/whiplash/
tt1821480               http://kahaanithefilm.com/
tt1380152                              Not Present
tt1375666            https://example.com/inception
tt0468569                              Not Present
tt1187043              https://example.com/3idiots
tt6751668                              Not Present
tt0362227     http://www.theterminal-themovie.com/
tt0105327                              Not Present
tt0109403                              Not Present
tt2364975                              Not Present
tt0116908                              Not Present
tt0343135           http://www.alongcamepolly.com/
tt1600195         http://www.abductionthefilm.com/
tt0816692                              Not Present
tt5074352                              Not Present
tt4154796                              Not Present
tt0120338                              Not Present
tt0245429             https://example.com/spirited
tt0068646                              Not Present
tt9000001                              Not Present
tt9000002                              Not Present
tt15327088             https://example.com/kantara
tt8178634                              Not Present
tt4849438                              Not Present
tt7286456                              Not Present
tt3783958                              Not Present
tt0112870                              Not Present
Name: homepage, dtype: str

In [78]:
df.head()

,belongs_to_collection,budget,genres,homepage,original_language,original_title,overview,popularity,production_companies,production_countries,...,status,tagline,title,Keywords,cast,revenue,movie_profit,Capitalized_title,new_profit,new_release_date
imdb_id,,,,,,,,,,,,,,,,,,,,,
tt2637294,Hot Tub Time Machine 2,14000000,"[{""name"": ""Comedy""}]",NaN,en,Hot Tub Time Machine 2,Time travel comedy.,6.575393,"[{""name"": ""Paramount Pictures""}]","[{""iso_3166_1"": ""US""}]",...,Released,The Laws of Space and Time,Hot Tub Time Machine 2,time travel,"[{""name"": ""Rob Corddry""}]",NaN,-1685349,HOT TUB TIME MACHINE 2,NaN,2015-02-20
tt0368933,The Princess Diaries 2: Royal Engagement,40000000,"[{""name"": ""Comedy""}, {""name"": ""Drama""}]",NaN,en,The Princess Diaries 2: Royal Engagement,A princess prepares for marriage.,8.248895,"[{""name"": ""Walt Disney Pictures""}]","[{""iso_3166_1"": ""US""}]",...,Released,It can take a lifetime to find true love.,The Princess Diaries 2: Royal Engagement,princess|royalty,"[{""name"": ""Anne Hathaway""}]",NaN,55149435,THE PRINCESS DIARIES 2: ROYAL ENGAGEMENT,NaN,2004-08-06
tt2582802,Whiplash,3300000,"[{""name"": ""Drama""}]",http://sonyclassics.com/whiplash/,en,Whiplash,A young drummer faces a ruthless instructor.,64.299990,"[{""name"": ""Bold Films""}]","[{""iso_3166_1"": ""US""}]",...,Released,The road to greatness can take you to the edge.,Whiplash,jazz|music,"[{""name"": ""Miles Teller""}]",13092000.0,9792000,WHIPLASH,9792000.0,2014-10-10
tt1821480,Kahaani,1200000,"[{""name"": ""Thriller""}, {""name"": ""Drama""}]",http://kahaanithefilm.com/,hi,Kahaani,A woman searches for her missing husband in Ko...,3.174936,NaN,"[{""iso_3166_1"": ""IN""}]",...,Released,NaN,Kahaani,mystery|kolkata,"[{""name"": ""Vidya Balan""}]",16000000.0,14800000,KAHAANI,14800000.0,2012-03-09
tt1380152,Marine Boy,0,"[{""name"": ""Action""}, {""name"": ""Thriller""}]",NaN,ko,Marine Boy,A former swimmer becomes involved in crime.,1.148070,NaN,"[{""iso_3166_1"": ""KR""}]",...,Released,NaN,Marine Boy,NaN,"[{""name"": ""Kim Kang-woo""}]",3923970.0,3923970,MARINE BOY,3923970.0,2009-02-05