In [4]:
import pandas as pd

from sklearn.datasets import load_breast_cancer

In [8]:
data=load_breast_cancer(as_frame=True)

data

{'data':      mean radius  mean texture  ...  worst symmetry  worst fractal dimension
 0          17.99         10.38  ...          0.4601                  0.11890
 1          20.57         17.77  ...          0.2750                  0.08902
 2          19.69         21.25  ...          0.3613                  0.08758
 3          11.42         20.38  ...          0.6638                  0.17300
 4          20.29         14.34  ...          0.2364                  0.07678
 ..           ...           ...  ...             ...                      ...
 564        21.56         22.39  ...          0.2060                  0.07115
 565        20.13         28.25  ...          0.2572                  0.06637
 566        16.60         28.08  ...          0.2218                  0.07820
 567        20.60         29.33  ...          0.4087                  0.12400
 568         7.76         24.54  ...          0.2871                  0.07039

 [569 rows x 30 columns],
 'target': 0      0
 1      0
 2      0
 3      0
 4      0
       ..
 564    0
 565    0
 566    0
 567    0
 568    1
 Name: target, Length: 569, dtype: int64,
 'frame':      mean radius  mean texture  ...  worst fractal dimension  target
 0          17.99         10.38  ...                  0.11890       0
 1          20.57         17.77  ...                  0.08902       0
 2          19.69         21.25  ...                  0.08758       0
 3          11.42         20.38  ...                  0.17300       0
 4          20.29         14.34  ...                  0.07678       0
 ..           ...           ...  ...                      ...     ...
 564        21.56         22.39  ...                  0.07115       0
 565        20.13         28.25  ...                  0.06637       0
 566        16.60         28.08  ...                  0.07820       0
 567        20.60         29.33  ...                  0.12400       0
 568         7.76         24.54  ...                  0.07039       1

 [569 rows x 31 columns],
 'target_names': array(['malignant', 'benign'], dtype='<U9'),
 'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer Wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 569\n\n:Number of Attributes: 30 numeric, predictive attributes and the class\n\n:Attribute Information:\n    - radius (mean of distances from center to points on the perimeter)\n    - texture (standard deviation of gray-scale values)\n    - perimeter\n    - area\n    - smoothness (local variation in radius lengths)\n    - compactness (perimeter^2 / area - 1.0)\n    - concavity (severity of concave portions of the contour)\n    - concave points (number of concave portions of the contour)\n    - symmetry\n    - fractal dimension ("coastline approximation" - 1)\n\n    The mean, standard error, and "worst" or largest (mean of the three\n    worst/largest values) of these features were computed for each image,\n    resulting in 30 features.  For instance, field 0 is Mean Radius, field\n    10 is Radius SE, field 20 is Worst Radius.\n\n    - class:\n            - WDBC-Malignant\n            - WDBC-Benign\n\n:Summary Statistics:\n\n===================================== ====== ======\n                                        Min    Max\n===================================== ====== ======\nradius (mean):                        6.981  28.11\ntexture (mean):                       9.71   39.28\nperimeter (mean):                     43.79  188.5\narea (mean):                          143.5  2501.0\nsmoothness (mean):                    0.053  0.163\ncompactness (mean):                   0.019  0.345\nconcavity (mean):                     0.0    0.427\nconcave points (mean):                0.0    0.201\nsymmetry (mean):                      0.106  0.304\nfractal dimension (mean):             0.05   0.097\nradius (standard error):              0.112  2.873\ntexture (standard error):             0.36   4.885\nperimeter (standard error):           0.757  21.98\narea (standard error):                6.802  542.2\nsmoothness (standard error):          0.002  0.031\ncompactness (standard error):         0.002  0.135\nconcavity (standard error):           0.0    0.396\nconcave points (standard error):      0.0    0.053\nsymmetry (standard error):            0.008  0.079\nfractal dimension (standard error):   0.001  0.03\nradius (worst):                       7.93   36.04\ntexture (worst):                      12.02  49.54\nperimeter (worst):                    50.41  251.2\narea (worst):                         185.2  4254.0\nsmoothness (worst):                   0.071  0.223\ncompactness (worst):                  0.027  1.058\nconcavity (worst):                    0.0    1.252\nconcave points (worst):               0.0    0.291\nsymmetry (worst):                     0.156  0.664\nfractal dimension (worst):            0.055  0.208\n===================================== ====== ======\n\n:Missing Attribute Values: None\n\n:Class Distribution: 212 - Malignant, 357 - Benign\n\n:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n:Donor: Nick Street\n\n:Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. dropdown:: References\n\n  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction\n    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on\n    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n    San Jose, CA, 1993.\n  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and\n    prognosis via linear programming. Operations Research, 43(4), pages 570-577,\n    July-August 1995.\n  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)\n    163-171.\n',
 'feature_names': array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
        'mean smoothness', 'mean compactness', 'mean concavity',
        'mean concave points', 'mean symmetry', 'mean fractal dimension',
        'radius error', 'texture error', 'perimeter error', 'area error',
        'smoothness error', 'compactness error', 'concavity error',
        'concave points error', 'symmetry error',
        'fractal dimension error', 'worst radius', 'worst texture',
        'worst perimeter', 'worst area', 'worst smoothness',
        'worst compactness', 'worst concavity', 'worst concave points',
        'worst symmetry', 'worst fractal dimension'], dtype='<U23'),
 'filename': 'breast_cancer.csv',
 'data_module': 'sklearn.datasets.data'}

In [9]:
X=data.data

y=data.target

In [10]:
X

     mean radius  mean texture  ...  worst symmetry  worst fractal dimension
0          17.99         10.38  ...          0.4601                  0.11890
1          20.57         17.77  ...          0.2750                  0.08902
2          19.69         21.25  ...          0.3613                  0.08758
3          11.42         20.38  ...          0.6638                  0.17300
4          20.29         14.34  ...          0.2364                  0.07678
..           ...           ...  ...             ...                      ...
564        21.56         22.39  ...          0.2060                  0.07115
565        20.13         28.25  ...          0.2572                  0.06637
566        16.60         28.08  ...          0.2218                  0.07820
567        20.60         29.33  ...          0.4087                  0.12400
568         7.76         24.54  ...          0.2871                  0.07039

[569 rows x 30 columns]

In [11]:
y

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: target, Length: 569, dtype: int64

In [12]:
from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [14]:
X_train

     mean radius  mean texture  ...  worst symmetry  worst fractal dimension
546        10.32         16.35  ...          0.2681                  0.07399
432        20.18         19.54  ...          0.3032                  0.08075
174        10.66         15.15  ...          0.2710                  0.06164
221        13.56         13.90  ...          0.3065                  0.08177
289        11.37         18.89  ...          0.3267                  0.06994
..           ...           ...  ...             ...                      ...
184        15.28         22.41  ...          0.3175                  0.09772
300        19.53         18.90  ...          0.2968                  0.09929
509        15.46         23.95  ...          0.3013                  0.10670
230        17.05         19.08  ...          0.3109                  0.09061
474        10.88         15.62  ...          0.2581                  0.10800

[455 rows x 30 columns]

In [15]:
y_train

546    1
432    0
174    1
221    1
289    1
      ..
184    0
300    0
509    0
230    0
474    1
Name: target, Length: 455, dtype: int64

In [16]:
X_test

     mean radius  mean texture  ...  worst symmetry  worst fractal dimension
256        19.55         28.77  ...          0.2818                  0.10050
428        11.13         16.62  ...          0.2383                  0.07083
501        13.82         24.49  ...          0.3651                  0.11830
363        16.50         18.29  ...          0.2394                  0.06469
564        21.56         22.39  ...          0.2060                  0.07115
..           ...           ...  ...             ...                      ...
95         20.26         23.03  ...          0.3689                  0.08368
128        15.10         16.39  ...          0.2590                  0.07779
257        15.32         17.27  ...          0.3258                  0.11910
228        12.62         23.97  ...          0.2826                  0.09585
488        11.68         16.17  ...          0.2804                  0.08024

[114 rows x 30 columns]

In [17]:
y_test

256    0
428    1
501    0
363    1
564    0
      ..
95     0
128    1
257    0
228    1
488    1
Name: target, Length: 114, dtype: int64

In [18]:
from sklearn.pipeline import make_pipeline

from sklearn.preprocessing import StandardScaler

In [19]:
# create the pipeline()


model=make_pipeline(StandardScaler(),LogisticRegression(max_iter=1000))

In [20]:
# train the model

model.fit(X_train,y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression(max_iter=1000))])

In [21]:
# make prediction


y_pred=model.predict(X_test)

In [22]:
y_test

256    0
428    1
501    0
363    1
564    0
      ..
95     0
128    1
257    0
228    1
488    1
Name: target, Length: 114, dtype: int64

In [24]:
y_pred

array([0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1])